import Foundation
import NaturalLanguage
import SwiftData
import OSLog

private let logger = Logger(subsystem: "com.kinen.app", category: "AIJournalingLoop")

/// Implements the 5-step AI Journaling Loop (industry best practice from Woebot/Wysa research).
///
/// 1. Raw Entry → user writes freely
/// 2. AI Reflection → instant emotion labels + cognitive distortion detection + summary
/// 3. Pattern Tagging → auto-categorize by life themes
/// 4. Micro-Experiments → suggest small actionable steps
/// 5. Therapist Integration → generate exportable summaries
///
/// All processing is on-device using Apple NaturalLanguage framework.
actor AIJournalingLoop {
    static let shared = AIJournalingLoop()

    private init() {}

    /// Run the full 5-step analysis on a journal entry.
    @MainActor
    func processEntry(_ entry: JournalEntry, in context: ModelContext) async {
        let content = entry.content
        logger.info("Processing entry through AI Journaling Loop...")

        // Step 2: AI Reflection — emotion labels + distortions + summary
        let sentiment = SentimentAnalyzer.shared.analyzeSentiment(content)
        entry.sentimentScore = sentiment

        let distortions = CBTReflection.analyze(content)
        if let primary = distortions.first, primary.confidence > 0.3 {
            let insight = EntryInsight(
                type: .pattern,
                content: "Noticed **\(primary.type.rawValue)**: \(primary.type.description). \(primary.reframing)"
            )
            entry.insights.append(insight)
        }

        // Step 3: Pattern Tagging — categorize by life themes
        let themes = detectLifeThemes(content)
        for theme in themes.prefix(3) {
            let descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == theme })
            let existing = (try? context.fetch(descriptor)) ?? []
            if let tag = existing.first {
                if !entry.tags.contains(where: { $0.id == tag.id }) {
                    entry.tags.append(tag)
                }
            } else {
                let newTag = Tag(name: theme, colorHex: themeColor(theme), isAutoGenerated: true)
                context.insert(newTag)
                entry.tags.append(newTag)
            }
        }

        // Step 2 continued: Topic extraction
        let topics = SentimentAnalyzer.shared.extractTopics(content)
        if !topics.isEmpty {
            let topicList = topics.prefix(5).joined(separator: ", ")
            let insight = EntryInsight(type: .topicExtraction, content: "Main topics: \(topicList)")
            entry.insights.append(insight)
        }

        // Step 4: Micro-Experiments — suggest actions
        let suggestion = generateMicroExperiment(sentiment: sentiment, distortions: distortions, themes: themes)
        if let suggestion {
            let insight = EntryInsight(type: .suggestion, content: suggestion)
            entry.insights.append(insight)
        }

        // Sentiment insight
        if sentiment > 0.3 {
            entry.insights.append(EntryInsight(type: .sentiment, content: "This entry radiates positivity! Noting what brings you joy helps you recreate it."))
        } else if sentiment < -0.3 {
            entry.insights.append(EntryInsight(type: .sentiment, content: "Tough feelings are valid. Writing about them is already a healthy step. Be kind to yourself."))
        }

        logger.info("AI Loop complete: sentiment=\(sentiment, format: .fixed(precision: 2)), themes=\(themes), distortions=\(distortions.count)")
    }

    // MARK: - Life Theme Detection

    /// Detect broad life themes in text using keyword matching + NLP.
    nonisolated func detectLifeThemes(_ text: String) -> [String] {
        let lowered = text.lowercased()
        var themes: [(theme: String, score: Int)] = []

        for (theme, keywords) in themeKeywords {
            let matchCount = keywords.filter { lowered.contains($0) }.count
            if matchCount > 0 {
                themes.append((theme, matchCount))
            }
        }

        return themes.sorted { $0.score > $1.score }.map { $0.theme }
    }

    private let themeKeywords: [String: [String]] = [
        "work": ["work", "job", "office", "boss", "colleague", "meeting", "deadline", "project", "career", "promotion", "salary", "工作", "上班", "公司", "老板"],
        "relationships": ["friend", "family", "partner", "love", "argument", "together", "lonely", "relationship", "boyfriend", "girlfriend", "husband", "wife", "朋友", "家人", "爱人", "关系"],
        "health": ["exercise", "gym", "run", "sleep", "tired", "sick", "doctor", "medicine", "headache", "anxiety", "meditation", "运动", "健康", "睡觉", "生病"],
        "finance": ["money", "budget", "save", "spend", "expensive", "debt", "salary", "investment", "钱", "花费", "存钱"],
        "growth": ["learn", "read", "study", "course", "skill", "improve", "goal", "achieve", "progress", "学习", "进步", "目标"],
        "creativity": ["write", "draw", "paint", "music", "create", "design", "build", "art", "创作", "设计", "音乐"],
        "travel": ["travel", "trip", "flight", "hotel", "city", "country", "vacation", "adventure", "旅行", "旅游"],
        "self-doubt": ["can't", "failure", "not good enough", "imposter", "worthless", "stupid", "ugly", "失败", "不够好"],
    ]

    nonisolated private func themeColor(_ theme: String) -> String {
        switch theme {
        case "work": return "3B82F6"       // blue
        case "relationships": return "EC4899" // pink
        case "health": return "10B981"      // green
        case "finance": return "F59E0B"     // amber
        case "growth": return "8B5CF6"      // purple
        case "creativity": return "F97316"  // orange
        case "travel": return "06B6D4"      // cyan
        case "self-doubt": return "6B7280"  // gray
        default: return "8B5CF6"            // purple
        }
    }

    // MARK: - Micro-Experiments

    nonisolated private func generateMicroExperiment(
        sentiment: Double,
        distortions: [DetectedDistortion],
        themes: [String]
    ) -> String? {
        // If negative sentiment + distortions → CBT-based suggestion
        if sentiment < -0.2, let distortion = distortions.first {
            return cbtExperiments[distortion.type]?.randomElement()
        }

        // Theme-based suggestions
        if let primaryTheme = themes.first {
            return themeExperiments[primaryTheme]?.randomElement()
        }

        // General positive suggestion
        if sentiment > 0.3 {
            return positiveExperiments.randomElement()
        }

        return nil
    }

    private let cbtExperiments: [CBTReflection.CognitiveDistortion: [String]] = [
        .catastrophizing: [
            "Try this: Write down the worst case, best case, and most likely case. Focus on the most likely.",
            "Set a 5-minute worry timer. When it rings, shift to one action you can take right now.",
        ],
        .allOrNothing: [
            "Challenge: Rate the situation on a 1-10 scale instead of pass/fail.",
            "Find one exception to the 'always' or 'never' pattern you noticed.",
        ],
        .shouldStatements: [
            "Replace each 'should' with 'I'd like to' or 'It would be nice if'. Notice how it changes the pressure.",
        ],
        .personalization: [
            "List 3 factors outside your control that contributed to this situation.",
        ],
        .mindReading: [
            "Instead of assuming what they think, consider asking them directly. What's the worst that could happen?",
        ],
        .overgeneralization: [
            "Can you think of one time when this didn't happen? Write it down.",
        ],
        .emotionalReasoning: [
            "Separate feeling from fact: 'I feel anxious' vs 'Something bad will happen'. They're not the same.",
        ],
        .labeling: [
            "Replace the label with specific behavior: Instead of 'I'm lazy', try 'I didn't finish the report today'.",
        ],
    ]

    private let themeExperiments: [String: [String]] = [
        "work": ["Take a 5-minute break to step outside. Fresh air resets focus."],
        "relationships": ["Send a short message to someone you appreciate. Connection matters."],
        "health": ["Do 3 deep breaths right now: 4 seconds in, 7 hold, 8 out."],
        "self-doubt": ["Write down one thing you did well today, no matter how small."],
        "growth": ["Spend 10 minutes on something you're learning. Small steps compound."],
        "creativity": ["Doodle or freewrite for 5 minutes. No judgment, just flow."],
    ]

    private let positiveExperiments = [
        "You're in a good place. Consider sharing this positive energy with someone who might need it.",
        "Capture what made today good so you can intentionally recreate it.",
    ]
}
