import Foundation
import NaturalLanguage
import SwiftData
import OSLog

private let logger = Logger(subsystem: "com.jasonye.kinen", category: "AIJournalingLoop")

/// Implements the 5-step AI Journaling Loop (industry best practice from Woebot/Wysa research).
///
/// 1. Raw Entry → user writes freely
/// 2. AI Reflection → instant emotion labels + cognitive distortion detection + summary
/// 3. Pattern Tagging → auto-categorize by life themes
/// 4. Micro-Experiments → suggest small actionable steps
/// 5. Therapist Integration → generate exportable summaries
///
/// All processing is on-device using Apple NaturalLanguage framework.
actor AIJournalingLoop {
    static let shared = AIJournalingLoop()

    private init() {}

    /// Run the full 5-step analysis on a journal entry.
    @MainActor
    func processEntry(_ entry: JournalEntry, in context: ModelContext, enableSentiment: Bool = true, enableTags: Bool = true) async {
        let content = entry.content
        logger.info("Processing entry through AI Journaling Loop...")

        // Step 2: AI Reflection — emotion labels + distortions + summary
        guard enableSentiment else {
            logger.info("AI analysis disabled in settings")
            return
        }
        let sentiment = await SentimentAnalyzer.shared.analyzeSentiment(content)
        entry.sentimentScore = sentiment

        let distortions = CBTReflection.analyze(content)
        if let primary = distortions.first, primary.confidence > 0.3 {
            let insight = EntryInsight(
                type: .pattern,
                content: "Noticed **\(primary.type.rawValue)**: \(primary.type.description). \(primary.reframing)"
            )
            entry.addInsight(insight)
        }

        // Step 3: Pattern Tagging — categorize by life themes (if enabled)
        let themes = detectLifeThemes(content)
        guard enableTags else {
            logger.info("Auto-tagging disabled in settings")
            return
        }
        for theme in themes.prefix(3) {
            let descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == theme })
            let existing: [Tag]
            do {
                existing = try context.fetch(descriptor)
            } catch {
                logger.error("Failed to fetch tag '\(theme)': \(error)")
                existing = []
            }
            if let tag = existing.first {
                if !entry.safeTags.contains(where: { $0.id == tag.id }) {
                    entry.addTag(tag)
                }
            } else {
                let newTag = Tag(name: theme, colorHex: themeColor(theme), isAutoGenerated: true)
                context.insert(newTag)
                entry.addTag(newTag)
            }
        }

        // Step 2 continued: Topic extraction
        let topics = await SentimentAnalyzer.shared.extractTopics(content)
        if !topics.isEmpty {
            let topicList = topics.prefix(5).joined(separator: ", ")
            let insight = EntryInsight(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), topicList))
            entry.addInsight(insight)
        }

        // Step 4: Micro-Experiments — suggest actions
        let suggestion = generateMicroExperiment(sentiment: sentiment, distortions: distortions, themes: themes)
        if let suggestion {
            let insight = EntryInsight(type: .suggestion, content: suggestion)
            entry.addInsight(insight)
        }

        // Sentiment insight
        if sentiment > 0.3 {
            entry.addInsight(EntryInsight(type: .sentiment, content: String(localized: "ai.insight.positive")))
        } else if sentiment < -0.3 {
            entry.addInsight(EntryInsight(type: .sentiment, content: String(localized: "ai.insight.negative")))
        }

        logger.info("AI Loop complete: sentiment=\(sentiment, format: .fixed(precision: 2)), themes=\(themes), distortions=\(distortions.count)")
    }

    // MARK: - Life Theme Detection

    /// Detect broad life themes in text using keyword matching + NLP.
    nonisolated func detectLifeThemes(_ text: String) -> [String] {
        let lowered = text.lowercased()
        var themes: [(theme: String, score: Int)] = []

        for (theme, keywords) in themeKeywords {
            let matchCount = keywords.filter { lowered.contains($0) }.count
            if matchCount > 0 {
                themes.append((theme, matchCount))
            }
        }

        return themes.sorted { $0.score > $1.score }.map { $0.theme }
    }

    private let themeKeywords: [String: [String]] = [
        "work": ["work", "job", "office", "boss", "colleague", "meeting", "deadline", "project", "career", "promotion", "salary", "工作", "上班", "公司", "老板"],
        "relationships": ["friend", "family", "partner", "love", "argument", "together", "lonely", "relationship", "boyfriend", "girlfriend", "husband", "wife", "朋友", "家人", "爱人", "关系"],
        "health": ["exercise", "gym", "run", "sleep", "tired", "sick", "doctor", "medicine", "headache", "anxiety", "meditation", "运动", "健康", "睡觉", "生病"],
        "finance": ["money", "budget", "save", "spend", "expensive", "debt", "salary", "investment", "钱", "花费", "存钱"],
        "growth": ["learn", "read", "study", "course", "skill", "improve", "goal", "achieve", "progress", "学习", "进步", "目标"],
        "creativity": ["write", "draw", "paint", "music", "create", "design", "build", "art", "创作", "设计", "音乐"],
        "travel": ["travel", "trip", "flight", "hotel", "city", "country", "vacation", "adventure", "旅行", "旅游"],
        "self-doubt": ["can't", "failure", "not good enough", "imposter", "worthless", "stupid", "ugly", "失败", "不够好"],
    ]

    nonisolated private func themeColor(_ theme: String) -> String {
        switch theme {
        case "work": return "3B82F6"       // blue
        case "relationships": return "EC4899" // pink
        case "health": return "10B981"      // green
        case "finance": return "F59E0B"     // amber
        case "growth": return "8B5CF6"      // purple
        case "creativity": return "F97316"  // orange
        case "travel": return "06B6D4"      // cyan
        case "self-doubt": return "6B7280"  // gray
        default: return "8B5CF6"            // purple
        }
    }

    // MARK: - Micro-Experiments

    nonisolated private func generateMicroExperiment(
        sentiment: Double,
        distortions: [DetectedDistortion],
        themes: [String]
    ) -> String? {
        // If negative sentiment + distortions → CBT-based suggestion
        if sentiment < -0.2, let distortion = distortions.first {
            return cbtExperiments[distortion.type]?.randomElement()
        }

        // Theme-based suggestions
        if let primaryTheme = themes.first {
            return themeExperiments[primaryTheme]?.randomElement()
        }

        // General positive suggestion
        if sentiment > 0.3 {
            return positiveExperiments.randomElement()
        }

        return nil
    }

    private let cbtExperiments: [CBTReflection.CognitiveDistortion: [String]] = [
        .catastrophizing: [
            String(localized: "ai.cbt.catastrophizing.1"),
            String(localized: "ai.cbt.catastrophizing.2"),
        ],
        .allOrNothing: [
            String(localized: "ai.cbt.allOrNothing.1"),
            String(localized: "ai.cbt.allOrNothing.2"),
        ],
        .shouldStatements: [
            String(localized: "ai.cbt.shouldStatements.1"),
        ],
        .personalization: [
            String(localized: "ai.cbt.personalization.1"),
        ],
        .mindReading: [
            String(localized: "ai.cbt.mindReading.1"),
        ],
        .overgeneralization: [
            String(localized: "ai.cbt.overgeneralization.1"),
        ],
        .emotionalReasoning: [
            String(localized: "ai.cbt.emotionalReasoning.1"),
        ],
        .labeling: [
            String(localized: "ai.cbt.labeling.1"),
        ],
    ]

    private let themeExperiments: [String: [String]] = [
        "work": [String(localized: "ai.theme.work")],
        "relationships": [String(localized: "ai.theme.relationships")],
        "health": [String(localized: "ai.theme.health")],
        "self-doubt": [String(localized: "ai.theme.selfDoubt")],
        "growth": [String(localized: "ai.theme.growth")],
        "creativity": [String(localized: "ai.theme.creativity")],
    ]

    private let positiveExperiments = [
        String(localized: "ai.experiment.positive.1"),
        String(localized: "ai.experiment.positive.2"),
    ]
}
