import Foundation
import NaturalLanguage
import SwiftData
import OSLog

private let logger = Logger(subsystem: "com.kinen.app", category: "SentimentAnalyzer")

/// On-device sentiment and topic analysis using Apple's NaturalLanguage framework.
/// Zero model downloads, zero network calls, instant results.
actor SentimentAnalyzer {
    static let shared = SentimentAnalyzer()

    private let tagger = NLTagger(tagSchemes: [.sentimentScore, .nameType, .lemma])

    private init() {}

    /// Analyze a journal entry: sentiment score + auto-generated tags + insights.
    @MainActor
    func analyze(entry: JournalEntry, in context: ModelContext) async {
        let content = entry.content

        // 1. Sentiment analysis
        let sentiment = analyzeSentiment(content)
        entry.sentimentScore = sentiment

        // 2. Extract key topics/entities as auto-tags
        let topics = extractTopics(content)
        for topic in topics.prefix(5) {
            let descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == topic })
            let existingTags = (try? context.fetch(descriptor)) ?? []

            if let existingTag = existingTags.first {
                if !entry.tags.contains(where: { $0.id == existingTag.id }) {
                    entry.tags.append(existingTag)
                }
            } else {
                let newTag = Tag(name: topic, isAutoGenerated: true)
                context.insert(newTag)
                entry.tags.append(newTag)
            }
        }

        // 3. Generate insights
        if sentiment > 0.3 {
            let insight = EntryInsight(type: .sentiment, content: "This entry has a positive tone. Keep noting what makes you feel good!")
            entry.insights.append(insight)
        } else if sentiment < -0.3 {
            let insight = EntryInsight(type: .sentiment, content: "This entry reflects some difficult feelings. Remember, acknowledging emotions is a healthy practice.")
            entry.insights.append(insight)
        }

        if !topics.isEmpty {
            let topicList = topics.prefix(5).joined(separator: ", ")
            let insight = EntryInsight(type: .topicExtraction, content: "Main topics: \(topicList)")
            entry.insights.append(insight)
        }

        logger.info("Analyzed entry: sentiment=\(sentiment, format: .fixed(precision: 2)), topics=\(topics.count)")
    }

    // MARK: - Sentiment

    /// Returns a score from -1.0 (very negative) to 1.0 (very positive)
    nonisolated func analyzeSentiment(_ text: String) -> Double {
        let tagger = NLTagger(tagSchemes: [.sentimentScore])
        tagger.string = text

        let (sentimentTag, _) = tagger.tag(at: text.startIndex, unit: .paragraph, scheme: .sentimentScore)
        if let tag = sentimentTag, let score = Double(tag.rawValue) {
            return score
        }
        return 0.0
    }

    // MARK: - Topic Extraction

    /// Extract named entities and key nouns as topics
    nonisolated func extractTopics(_ text: String) -> [String] {
        let tagger = NLTagger(tagSchemes: [.nameType, .lexicalClass])
        tagger.string = text

        var topics: [String: Int] = [:]
        let options: NLTagger.Options = [.omitPunctuation, .omitWhitespace, .omitOther]

        // Extract named entities
        tagger.enumerateTags(in: text.startIndex..<text.endIndex, unit: .word, scheme: .nameType, options: options) { tag, range in
            if let tag, tag != .otherWord {
                let word = String(text[range]).trimmingCharacters(in: .whitespacesAndNewlines)
                if word.count > 2 {
                    topics[word.lowercased(), default: 0] += 2 // entities get double weight
                }
            }
            return true
        }

        // Extract nouns
        tagger.enumerateTags(in: text.startIndex..<text.endIndex, unit: .word, scheme: .lexicalClass, options: options) { tag, range in
            if tag == .noun {
                let word = String(text[range]).trimmingCharacters(in: .whitespacesAndNewlines)
                if word.count > 3 {
                    topics[word.lowercased(), default: 0] += 1
                }
            }
            return true
        }

        // Return top topics by frequency, excluding common words
        let stopWords: Set<String> = ["thing", "time", "today", "something", "someone", "nothing", "everything", "year", "month", "week"]
        return topics
            .filter { !stopWords.contains($0.key) }
            .sorted { $0.value > $1.value }
            .map { $0.key }
    }
}
