import SwiftUI
import SwiftData

struct TagManagementSheet: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    @Query(sort: \Tag.name) private var tags: [Tag]

    @State private var editingTag: Tag?
    @State private var newName = ""
    @State private var showDeleteConfirm = false
    @State private var tagToDelete: Tag?
    @State private var showMergeSheet = false
    @State private var mergeSource: Tag?

    var body: some View {
        NavigationStack {
            List {
                if tags.isEmpty {
                    ContentUnavailableView {
                        Label(String(localized: "tags.empty.title"), systemImage: "tag")
                    } description: {
                        Text(String(localized: "tags.empty.description"))
                    }
                } else {
                    ForEach(tags) { tag in
                        HStack {
                            Circle()
                                .fill(tag.color)
                                .frame(width: 12, height: 12)

                            if editingTag?.id == tag.id {
                                TextField("Tag name", text: $newName)
                                    .textFieldStyle(.plain)
                                    .onSubmit { finishEditing(tag: tag) }
                                Button(String(localized: "general.done")) { finishEditing(tag: tag) }
                                    .buttonStyle(.borderless)
                                    .foregroundStyle(.purple)
                            } else {
                                Text(tag.name)
                                    .font(.body)

                                Spacer()

                                Text("\(tag.entryCount)")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                                    .padding(.horizontal, 8)
                                    .padding(.vertical, 2)
                                    .background(.secondary.opacity(0.1))
                                    .clipShape(Capsule())

                                if tag.isAutoGenerated {
                                    Image(systemName: "sparkles")
                                        .font(.caption2)
                                        .foregroundStyle(.purple)
                                        .help("Auto-generated by AI")
                                }
                            }
                        }
                        .contextMenu {
                            Button(String(localized: "tags.rename")) {
                                editingTag = tag
                                newName = tag.name
                            }
                            Button(String(localized: "tags.merge")) {
                                mergeSource = tag
                                showMergeSheet = true
                            }
                            Divider()
                            Button(String(localized: "general.delete"), role: .destructive) {
                                tagToDelete = tag
                                showDeleteConfirm = true
                            }
                        }
                        .swipeActions(edge: .trailing) {
                            Button(role: .destructive) {
                                tagToDelete = tag
                                showDeleteConfirm = true
                            } label: {
                                Label(String(localized: "general.delete"), systemImage: "trash")
                            }
                            Button {
                                editingTag = tag
                                newName = tag.name
                            } label: {
                                Label(String(localized: "tags.rename"), systemImage: "pencil")
                            }
                            .tint(.purple)
                        }
                    }
                }
            }
            .navigationTitle(String(localized: "tags.manage.\(tags.count)"))
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(String(localized: "general.done")) { dismiss() }
                }
            }
            .alert(String(localized: "tags.delete.title"), isPresented: $showDeleteConfirm) {
                Button(String(localized: "general.delete"), role: .destructive) {
                    if let tag = tagToDelete {
                        modelContext.delete(tag)
                    }
                }
                Button(String(localized: "general.cancel"), role: .cancel) {}
            } message: {
                Text(String(localized: "tags.delete.message"))
            }
            .sheet(isPresented: $showMergeSheet) {
                if let source = mergeSource {
                    TagMergeSheet(sourceTag: source, allTags: tags.filter { $0.id != source.id })
                }
            }
        }
        #if os(macOS)
        .frame(minWidth: 340, idealWidth: 400, minHeight: 300, idealHeight: 350)
        #endif
    }

    private func finishEditing(tag: Tag) {
        let trimmed = newName.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if !trimmed.isEmpty {
            tag.name = trimmed
        }
        editingTag = nil
        newName = ""
    }
}

// MARK: - Merge Sheet

struct TagMergeSheet: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    let sourceTag: Tag
    let allTags: [Tag]
    @State private var selectedTarget: Tag?

    var body: some View {
        NavigationStack {
            VStack(alignment: .leading, spacing: 16) {
                Text(String(localized: "tags.merge.into.\(sourceTag.name)"))
                    .font(.headline)

                List(allTags, selection: $selectedTarget) { tag in
                    HStack {
                        Circle().fill(tag.color).frame(width: 10, height: 10)
                        Text(tag.name)
                        Spacer()
                        Text("\(tag.entryCount) \(String(localized: "general.entries"))").font(.caption).foregroundStyle(.secondary)
                    }
                    .tag(tag)
                }

                Button(String(localized: "tags.merge.action")) {
                    guard let target = selectedTarget else { return }
                    // Move all entries from source to target
                    for entry in sourceTag.safeEntries {
                        if !target.safeEntries.contains(where: { $0.id == entry.id }) {
                            if target.entries != nil { target.entries!.append(entry) }
                            else { target.entries = [entry] }
                        }
                    }
                    modelContext.delete(sourceTag)
                    dismiss()
                }
                .buttonStyle(.borderedProminent)
                .tint(.purple)
                .disabled(selectedTarget == nil)
            }
            .padding()
            .navigationTitle(String(localized: "tags.merge.title"))
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button(String(localized: "general.cancel")) { dismiss() }
                }
            }
        }
        #if os(macOS)
        .frame(minWidth: 300, idealWidth: 350, minHeight: 260, idealHeight: 300)
        #endif
    }
}
