import SwiftUI
import SwiftData

struct TagManagementSheet: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    @Query(sort: \Tag.name) private var tags: [Tag]

    @State private var editingTag: Tag?
    @State private var newName = ""
    @State private var showDeleteConfirm = false
    @State private var tagToDelete: Tag?
    @State private var showMergeSheet = false
    @State private var mergeSource: Tag?

    var body: some View {
        NavigationStack {
            List {
                if tags.isEmpty {
                    ContentUnavailableView {
                        Label("No Tags", systemImage: "tag")
                    } description: {
                        Text("Tags are created automatically by AI when you write entries, or you can add them manually in the editor.")
                    }
                } else {
                    ForEach(tags) { tag in
                        HStack {
                            Circle()
                                .fill(tag.color)
                                .frame(width: 12, height: 12)

                            if editingTag?.id == tag.id {
                                TextField("Tag name", text: $newName)
                                    .textFieldStyle(.plain)
                                    .onSubmit { finishEditing(tag: tag) }
                                Button("Done") { finishEditing(tag: tag) }
                                    .buttonStyle(.borderless)
                                    .foregroundStyle(.purple)
                            } else {
                                Text(tag.name)
                                    .font(.body)

                                Spacer()

                                Text("\(tag.entryCount)")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                                    .padding(.horizontal, 8)
                                    .padding(.vertical, 2)
                                    .background(.secondary.opacity(0.1))
                                    .clipShape(Capsule())

                                if tag.isAutoGenerated {
                                    Image(systemName: "sparkles")
                                        .font(.caption2)
                                        .foregroundStyle(.purple)
                                        .help("Auto-generated by AI")
                                }
                            }
                        }
                        .contextMenu {
                            Button("Rename") {
                                editingTag = tag
                                newName = tag.name
                            }
                            Button("Merge into...") {
                                mergeSource = tag
                                showMergeSheet = true
                            }
                            Divider()
                            Button("Delete", role: .destructive) {
                                tagToDelete = tag
                                showDeleteConfirm = true
                            }
                        }
                        .swipeActions(edge: .trailing) {
                            Button(role: .destructive) {
                                tagToDelete = tag
                                showDeleteConfirm = true
                            } label: {
                                Label("Delete", systemImage: "trash")
                            }
                            Button {
                                editingTag = tag
                                newName = tag.name
                            } label: {
                                Label("Rename", systemImage: "pencil")
                            }
                            .tint(.purple)
                        }
                    }
                }
            }
            .navigationTitle("Manage Tags (\(tags.count))")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Done") { dismiss() }
                }
            }
            .alert("Delete Tag?", isPresented: $showDeleteConfirm) {
                Button("Delete", role: .destructive) {
                    if let tag = tagToDelete {
                        modelContext.delete(tag)
                    }
                }
                Button("Cancel", role: .cancel) {}
            } message: {
                Text("This tag will be removed from all entries. This cannot be undone.")
            }
            .sheet(isPresented: $showMergeSheet) {
                if let source = mergeSource {
                    TagMergeSheet(sourceTag: source, allTags: tags.filter { $0.id != source.id })
                }
            }
        }
        #if os(macOS)
        .frame(minWidth: 400, minHeight: 350)
        #endif
    }

    private func finishEditing(tag: Tag) {
        let trimmed = newName.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if !trimmed.isEmpty {
            tag.name = trimmed
        }
        editingTag = nil
        newName = ""
    }
}

// MARK: - Merge Sheet

struct TagMergeSheet: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    let sourceTag: Tag
    let allTags: [Tag]
    @State private var selectedTarget: Tag?

    var body: some View {
        NavigationStack {
            VStack(alignment: .leading, spacing: 16) {
                Text("Merge \"\(sourceTag.name)\" into:")
                    .font(.headline)

                List(allTags, selection: $selectedTarget) { tag in
                    HStack {
                        Circle().fill(tag.color).frame(width: 10, height: 10)
                        Text(tag.name)
                        Spacer()
                        Text("\(tag.entryCount) entries").font(.caption).foregroundStyle(.secondary)
                    }
                    .tag(tag)
                }

                Button("Merge") {
                    guard let target = selectedTarget else { return }
                    // Move all entries from source to target
                    for entry in sourceTag.entries {
                        if !target.entries.contains(where: { $0.id == entry.id }) {
                            target.entries.append(entry)
                        }
                    }
                    modelContext.delete(sourceTag)
                    dismiss()
                }
                .buttonStyle(.borderedProminent)
                .tint(.purple)
                .disabled(selectedTarget == nil)
            }
            .padding()
            .navigationTitle("Merge Tag")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
            }
        }
        #if os(macOS)
        .frame(minWidth: 350, minHeight: 300)
        #endif
    }
}
