import Foundation
import SwiftData
import SwiftUI

@Model
final class Tag {
    var id: UUID
    var name: String
    var colorHex: String
    var isAutoGenerated: Bool
    var createdAt: Date

    var entries: [JournalEntry]

    init(name: String, colorHex: String = "8B5CF6", isAutoGenerated: Bool = false) {
        self.id = UUID()
        self.name = name.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        self.colorHex = colorHex
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = Date()
        self.entries = []
    }

    var color: Color {
        Color(hex: colorHex)
    }

    var entryCount: Int {
        entries.count
    }
}

// MARK: - Color Extension

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let r, g, b: UInt64
        switch hex.count {
        case 6:
            (r, g, b) = ((int >> 16) & 0xFF, (int >> 8) & 0xFF, int & 0xFF)
        default:
            (r, g, b) = (139, 92, 246) // fallback purple
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: 1
        )
    }
}
