import XCTest
import SwiftData
@testable import Kinen

final class BackupServiceTests: XCTestCase {

    private var container: ModelContainer!
    private var context: ModelContext!

    override func setUp() {
        super.setUp()
        let schema = Schema([JournalEntry.self, Tag.self, EntryInsight.self, WritingSession.self])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        container = try! ModelContainer(for: schema, configurations: [config])
        context = ModelContext(container)
    }

    override func tearDown() {
        context = nil
        container = nil
        super.tearDown()
    }

    // MARK: - Encrypt / Decrypt Cycle

    func testEncryptDecryptRoundTrip() throws {
        let entry = JournalEntry(content: "Test entry content", title: "My Title", mood: .great)
        entry.isBookmarked = true
        entry.sentimentScore = 0.75
        context.insert(entry)

        let tag = Tag(name: "work", colorHex: "#FF0000", isAutoGenerated: false)
        context.insert(tag)
        entry.addTag(tag)

        let insight = EntryInsight(type: .sentiment, content: "Positive tone")
        entry.addInsight(insight)

        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())

        // Create encrypted backup
        let password = "test-password-123"
        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: password)
        XCTAssertFalse(encrypted.isEmpty, "Encrypted data should not be empty")

        // Restore into a fresh context
        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        let importedCount = try BackupService.restoreBackup(data: encrypted, password: password, context: restoreContext)
        try restoreContext.save()

        XCTAssertEqual(importedCount, 1, "Should import 1 entry")

        let restoredEntries = try restoreContext.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(restoredEntries.count, 1)

        let restored = restoredEntries[0]
        XCTAssertEqual(restored.content, "Test entry content")
        XCTAssertEqual(restored.title, "My Title")
        XCTAssertEqual(restored.mood, .great)
        XCTAssertEqual(restored.isBookmarked, true)
        XCTAssertEqual(restored.sentimentScore, 0.75)

        // Tags restored
        let restoredTags = try restoreContext.fetch(FetchDescriptor<Tag>())
        XCTAssertEqual(restoredTags.count, 1)
        XCTAssertEqual(restoredTags[0].name, "work")

        // Tag relationship restored
        XCTAssertEqual(restored.safeTags.count, 1)
        XCTAssertEqual(restored.safeTags.first?.name, "work")

        // Insights restored
        XCTAssertEqual(restored.safeInsights.count, 1)
        XCTAssertEqual(restored.safeInsights.first?.type, .sentiment)
    }

    // MARK: - Wrong Password

    func testDecryptWithWrongPasswordFails() throws {
        let entry = JournalEntry(content: "Secret diary entry")
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "correct-password")

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        XCTAssertThrowsError(
            try BackupService.restoreBackup(data: encrypted, password: "wrong-password", context: restoreContext),
            "Decryption with wrong password should throw"
        )
    }

    // MARK: - Corrupted Data

    func testDecryptCorruptedDataFails() throws {
        let corruptedData = Data([0x00, 0x01, 0x02, 0x03]) // Too short for salt + sealed box
        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        XCTAssertThrowsError(
            try BackupService.restoreBackup(data: corruptedData, password: "any-password", context: restoreContext),
            "Corrupted data should throw"
        )
    }

    // MARK: - Duplicate Skip

    func testRestoreSkipsDuplicateEntries() throws {
        let entry = JournalEntry(content: "Original entry")
        let fixedId = entry.id
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "pass")

        // Restore into the SAME context (entry already exists)
        let importedCount = try BackupService.restoreBackup(data: encrypted, password: "pass", context: context)
        try context.save()

        XCTAssertEqual(importedCount, 0, "Should skip duplicate entry")

        let allEntries = try context.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(allEntries.count, 1, "Should still have only 1 entry")
        XCTAssertEqual(allEntries[0].id, fixedId)
    }

    // MARK: - Preview Backup

    func testPreviewBackupSucceeds() throws {
        let entry = JournalEntry(content: "Preview test")
        context.insert(entry)
        try context.save()
        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())

        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: "preview-pass")

        let preview = try BackupService.previewBackup(data: encrypted, password: "preview-pass")
        XCTAssertEqual(preview.entryCount, 1)
        XCTAssertEqual(preview.tagCount, 0)
        XCTAssertNotNil(preview.deviceName)
        XCTAssert(abs(preview.createdAt.timeIntervalSinceNow) < 5, "Creation date should be recent")
    }

    func testPreviewBackupFailsWithWrongPassword() throws {
        let entry = JournalEntry(content: "Preview test")
        context.insert(entry)
        try context.save()
        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())

        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: "correct-pass")

        XCTAssertThrowsError(try BackupService.previewBackup(data: encrypted, password: "wrong-pass"))
    }

    // MARK: - Empty Backup

    func testEmptyBackupRoundTrip() throws {
        let encrypted = try BackupService.createBackup(entries: [], tags: [], password: "pass")
        XCTAssertFalse(encrypted.isEmpty)

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        let importedCount = try BackupService.restoreBackup(data: encrypted, password: "pass", context: restoreContext)
        XCTAssertEqual(importedCount, 0)
    }
}
