import XCTest
import SwiftData
@testable import Kinen

final class BackupServiceTests: XCTestCase {

    private var container: ModelContainer!
    private var context: ModelContext!

    override func setUp() {
        super.setUp()
        let schema = Schema([JournalEntry.self, Tag.self, EntryInsight.self, WritingSession.self])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        container = try! ModelContainer(for: schema, configurations: [config])
        context = ModelContext(container)
    }

    override func tearDown() {
        context = nil
        container = nil
        super.tearDown()
    }

    // MARK: - Encrypt / Decrypt Cycle

    func testEncryptDecryptRoundTrip() throws {
        let entry = JournalEntry(content: "Test entry content", title: "My Title", mood: .great)
        entry.isBookmarked = true
        entry.sentimentScore = 0.75
        context.insert(entry)

        let tag = Tag(name: "work", colorHex: "#FF0000", isAutoGenerated: false)
        context.insert(tag)
        entry.addTag(tag)

        let insight = EntryInsight(type: .sentiment, content: "Positive tone")
        entry.addInsight(insight)

        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())

        // Create encrypted backup
        let password = "test-password-123"
        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: password)
        XCTAssertFalse(encrypted.isEmpty, "Encrypted data should not be empty")

        // Restore into a fresh context
        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        let importedCount = try BackupService.restoreBackup(data: encrypted, password: password, context: restoreContext)
        try restoreContext.save()

        XCTAssertEqual(importedCount, 1, "Should import 1 entry")

        let restoredEntries = try restoreContext.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(restoredEntries.count, 1)

        let restored = restoredEntries[0]
        XCTAssertEqual(restored.content, "Test entry content")
        XCTAssertEqual(restored.title, "My Title")
        XCTAssertEqual(restored.mood, .great)
        XCTAssertEqual(restored.isBookmarked, true)
        XCTAssertEqual(restored.sentimentScore, 0.75)

        // Tags restored
        let restoredTags = try restoreContext.fetch(FetchDescriptor<Tag>())
        XCTAssertEqual(restoredTags.count, 1)
        XCTAssertEqual(restoredTags[0].name, "work")

        // Tag relationship restored
        XCTAssertEqual(restored.safeTags.count, 1)
        XCTAssertEqual(restored.safeTags.first?.name, "work")

        // Insights restored
        XCTAssertEqual(restored.safeInsights.count, 1)
        XCTAssertEqual(restored.safeInsights.first?.type, .sentiment)
    }

    // MARK: - Wrong Password

    func testDecryptWithWrongPasswordFails() throws {
        let entry = JournalEntry(content: "Secret diary entry")
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "correct-password")

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        XCTAssertThrowsError(
            try BackupService.restoreBackup(data: encrypted, password: "wrong-password", context: restoreContext),
            "Decryption with wrong password should throw"
        )
    }

    // MARK: - Corrupted Data

    func testDecryptCorruptedDataFails() throws {
        let corruptedData = Data([0x00, 0x01, 0x02, 0x03]) // Too short for salt + sealed box
        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        XCTAssertThrowsError(
            try BackupService.restoreBackup(data: corruptedData, password: "any-password", context: restoreContext),
            "Corrupted data should throw"
        )
    }

    // MARK: - Duplicate Skip

    func testRestoreSkipsDuplicateEntries() throws {
        let entry = JournalEntry(content: "Original entry")
        let fixedId = entry.id
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "pass")

        // Restore into the SAME context (entry already exists)
        let importedCount = try BackupService.restoreBackup(data: encrypted, password: "pass", context: context)
        try context.save()

        XCTAssertEqual(importedCount, 0, "Should skip duplicate entry")

        let allEntries = try context.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(allEntries.count, 1, "Should still have only 1 entry")
        XCTAssertEqual(allEntries[0].id, fixedId)
    }

    // MARK: - Preview Backup

    func testPreviewBackupSucceeds() throws {
        let entry = JournalEntry(content: "Preview test")
        context.insert(entry)
        try context.save()
        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())

        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: "preview-pass")

        let preview = try BackupService.previewBackup(data: encrypted, password: "preview-pass")
        XCTAssertEqual(preview.entryCount, 1)
        XCTAssertEqual(preview.tagCount, 0)
        XCTAssertNotNil(preview.deviceName)
        XCTAssert(abs(preview.createdAt.timeIntervalSinceNow) < 5, "Creation date should be recent")
    }

    func testPreviewBackupFailsWithWrongPassword() throws {
        let entry = JournalEntry(content: "Preview test")
        context.insert(entry)
        try context.save()
        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())

        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: "correct-pass")

        XCTAssertThrowsError(try BackupService.previewBackup(data: encrypted, password: "wrong-pass"))
    }

    // MARK: - Empty Backup

    func testEmptyBackupRoundTrip() throws {
        let encrypted = try BackupService.createBackup(entries: [], tags: [], password: "pass")
        XCTAssertFalse(encrypted.isEmpty)

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        let importedCount = try BackupService.restoreBackup(data: encrypted, password: "pass", context: restoreContext)
        XCTAssertEqual(importedCount, 0)
    }

    // MARK: - v1.1 / v1.2 Optional Fields

    func testV12FieldsRoundTrip() throws {
        let entry = JournalEntry(content: "Draft content")
        entry.isHidden = true
        entry.isPinned = true
        entry.previousContent = "Earlier version"
        entry.template = .gratitude
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "pass")

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        let importedCount = try BackupService.restoreBackup(data: encrypted, password: "pass", context: restoreContext)
        XCTAssertEqual(importedCount, 1)

        let restored = try restoreContext.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(restored.count, 1)
        let r = restored[0]
        XCTAssertTrue(r.isHidden)
        XCTAssertTrue(r.isPinned)
        XCTAssertEqual(r.previousContent, "Earlier version")
        XCTAssertEqual(r.template, .gratitude)
    }

    // MARK: - Multiple Entries

    func testMultipleEntriesRoundTrip() throws {
        let e1 = JournalEntry(content: "First entry", mood: .great)
        let e2 = JournalEntry(content: "Second entry", mood: .terrible)
        let e3 = JournalEntry(content: "Third entry")
        context.insert(e1)
        context.insert(e2)
        context.insert(e3)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "multi")

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        let importedCount = try BackupService.restoreBackup(data: encrypted, password: "multi", context: restoreContext)
        XCTAssertEqual(importedCount, 3)

        let preview = try BackupService.previewBackup(data: encrypted, password: "multi")
        XCTAssertEqual(preview.entryCount, 3)
    }

    // MARK: - BackupError.errorDescription

    func testEncryptionFailedErrorDescription() {
        XCTAssertEqual(BackupError.encryptionFailed.errorDescription, "Failed to encrypt backup data")
    }

    func testDecryptionFailedErrorDescription() {
        XCTAssertEqual(BackupError.decryptionFailed.errorDescription, "Failed to decrypt backup. Check your password.")
    }

    func testInvalidPasswordErrorDescription() {
        XCTAssertEqual(BackupError.invalidPassword.errorDescription, "Incorrect password")
    }

    func testCorruptedDataErrorDescription() {
        XCTAssertEqual(BackupError.corruptedData.errorDescription, "Backup file is corrupted or invalid")
    }

    // MARK: - Tag Deduplication

    func testTagDeduplicationOnRestore() throws {
        let sharedTag = Tag(name: "shared-tag", colorHex: "#0000FF", isAutoGenerated: false)
        context.insert(sharedTag)
        let entry = JournalEntry(content: "Entry with existing tag")
        entry.addTag(sharedTag)
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let tags = try context.fetch(FetchDescriptor<Tag>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: tags, password: "pass")

        // Restore into context that already has the same tag
        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        // Pre-insert the tag so restoreBackup finds it already exists
        let preExistingTag = Tag(name: "shared-tag", colorHex: "#FF0000", isAutoGenerated: false)
        restoreContext.insert(preExistingTag)
        try restoreContext.save()

        _ = try BackupService.restoreBackup(data: encrypted, password: "pass", context: restoreContext)
        try restoreContext.save()

        let allTags = try restoreContext.fetch(FetchDescriptor<Tag>())
        XCTAssertEqual(allTags.count, 1, "Should not create a duplicate tag that already exists in context")
    }

    // MARK: - writingDuration Round-Trip

    func testWritingDurationRoundTrip() throws {
        let entry = JournalEntry(content: "Long writing session")
        entry.writingDuration = 420.5  // 7 minutes 0.5 seconds
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "duration-pass")

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        _ = try BackupService.restoreBackup(data: encrypted, password: "duration-pass", context: restoreContext)
        try restoreContext.save()

        let restored = try restoreContext.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(restored.count, 1)
        XCTAssertEqual(restored[0].writingDuration, 420.5,
                       "writingDuration should be preserved through backup/restore cycle")
    }

    // MARK: - Photo Data Round-Trip

    func testPhotoDataRoundTrip() throws {
        let entry = JournalEntry(content: "Entry with photo")
        entry.photoData = Data([0xFF, 0xD8, 0xFF, 0xE0, 0x01, 0x02])  // fake JPEG header bytes
        context.insert(entry)
        try context.save()

        let entries = try context.fetch(FetchDescriptor<JournalEntry>())
        let encrypted = try BackupService.createBackup(entries: entries, tags: [], password: "photo-pass")

        let restoreConfig = ModelConfiguration(schema: container.schema, isStoredInMemoryOnly: true)
        let restoreContainer = try ModelContainer(for: container.schema, configurations: [restoreConfig])
        let restoreContext = ModelContext(restoreContainer)

        _ = try BackupService.restoreBackup(data: encrypted, password: "photo-pass", context: restoreContext)
        try restoreContext.save()

        let restored = try restoreContext.fetch(FetchDescriptor<JournalEntry>())
        XCTAssertEqual(restored.count, 1)
        XCTAssertEqual(restored[0].photoData, Data([0xFF, 0xD8, 0xFF, 0xE0, 0x01, 0x02]),
                       "photoData should be preserved through backup/restore cycle via Base64 encoding")
    }
}
