import XCTest
@testable import Kinen

final class InsightEngineTests: XCTestCase {

    // MARK: - Helpers

    private func makeEntry(content: String = "test", mood: Mood? = nil, createdAt: Date = Date(), tags: [Tag] = []) -> JournalEntry {
        let entry = JournalEntry(content: content, mood: mood, tags: tags, createdAt: createdAt)
        return entry
    }

    private func daysAgo(_ n: Int) -> Date {
        Calendar.current.date(byAdding: .day, value: -n, to: Date())!
    }

    private func dateWithHour(_ hour: Int, daysAgo: Int = 0) -> Date {
        var comps = Calendar.current.dateComponents([.year, .month, .day], from: Date())
        comps.day! -= daysAgo
        comps.hour = hour
        comps.minute = 0
        comps.second = 0
        return Calendar.current.date(from: comps) ?? Date()
    }

    // MARK: - Basic Tests

    func testNoInsightsWithFewEntries() {
        let entries = (0..<3).map { _ in makeEntry(mood: .good) }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertTrue(insights.isEmpty, "Should not generate insights with <5 entries")
    }

    func testGeneratesInsightsWithEnoughEntries() {
        let entries = (0..<10).map { i in
            makeEntry(mood: i < 5 ? .great : .bad, createdAt: daysAgo(i))
        }
        // May or may not generate insights depending on patterns, but shouldn't crash
        _ = InsightEngine.generateInsights(from: entries)
    }

    func testEmptyEntriesReturnsEmpty() {
        let insights = InsightEngine.generateInsights(from: [])
        XCTAssertTrue(insights.isEmpty)
    }

    // MARK: - Consistency Insight

    func testConsistencyInsightForActiveWriter() {
        // Create entries for 26 of the last 30 days
        let entries = (0..<26).map { i in
            makeEntry(mood: .good, createdAt: daysAgo(i))
        }
        let insights = InsightEngine.generateInsights(from: entries)
        let consistencyInsight = insights.first { $0.type == .streak }
        XCTAssertNotNil(consistencyInsight, "Should detect high consistency")
    }

    // MARK: - Sporadic Writer

    func testInconsistencyInsightForSporadicWriter() {
        // 12 entries on only 2 unique days — uniqueDays (2) ≤ 5 + count (12) ≥ 10
        let day1 = daysAgo(5)
        let day2 = daysAgo(6)
        let entries = (0..<6).map { _ in makeEntry(mood: .good, createdAt: day1) } +
                      (0..<6).map { _ in makeEntry(mood: .neutral, createdAt: day2) }
        let insights = InsightEngine.generateInsights(from: entries)
        let streakInsight = insights.first { $0.type == .streak }
        XCTAssertNotNil(streakInsight, "Should detect sporadic writing pattern for user writing in bursts")
    }

    // MARK: - Word Count / Mood Correlation

    func testWordCountCorrelationLongerEntriesBetterMood() {
        // 6 one-word (terrible) + 6 ten-word (great) → longerBetter writingHabit
        let shortContent = "brief"
        let longContent = "one two three four five six seven eight nine ten"
        let entries = (0..<6).map { _ in makeEntry(content: shortContent, mood: .terrible) } +
                      (0..<6).map { _ in makeEntry(content: longContent,  mood: .great) }
        let insights = InsightEngine.generateInsights(from: entries)
        let habitInsight = insights.first { $0.type == .writingHabit }
        XCTAssertNotNil(habitInsight, "Should detect word count–mood correlation when longer entries have better mood")
    }

    func testWordCountCorrelationShorterEntriesBetterMood() {
        // 6 one-word (great) + 6 ten-word (terrible) → shorterBetter writingHabit
        let shortContent = "brief"
        let longContent = "one two three four five six seven eight nine ten"
        let entries = (0..<6).map { _ in makeEntry(content: shortContent, mood: .great) } +
                      (0..<6).map { _ in makeEntry(content: longContent,  mood: .terrible) }
        let insights = InsightEngine.generateInsights(from: entries)
        let habitInsight = insights.first { $0.type == .writingHabit }
        XCTAssertNotNil(habitInsight, "Should detect word count–mood correlation when shorter entries have better mood")
    }

    // MARK: - Mood Values

    func testMoodNormalizedValues() {
        XCTAssertEqual(Mood.terrible.normalizedValue, 0.0)
        XCTAssertEqual(Mood.great.normalizedValue, 1.0)
        XCTAssertGreaterThan(Mood.good.normalizedValue, Mood.neutral.normalizedValue)
    }

    // MARK: - Tag-Mood Correlation

    func testPositiveTagMoodCorrelation() {
        // 5 neutral (avg 0.5) + 3 great with "work" tag (avg 1.0)
        // overall avg = (5×0.5 + 3×1.0)/8 = 0.6875 — diff = 1.0−0.6875 = 0.3125 > 0.15
        let workTag = Tag(name: "work", colorHex: "#0000FF", isAutoGenerated: false)
        let neutralEntries = (0..<5).map { _ in makeEntry(mood: .neutral) }
        let workEntries = (0..<3).map { _ in makeEntry(mood: .great, tags: [workTag]) }
        let insights = InsightEngine.generateInsights(from: neutralEntries + workEntries)
        XCTAssertTrue(insights.contains { $0.type == .tagMoodCorrelation },
                      "Should detect positive tag-mood correlation when a tag strongly predicts better mood")
    }

    func testNegativeTagMoodCorrelation() {
        // 5 neutral (avg 0.5) + 3 terrible with "deadlines" tag (avg 0.0)
        // overall avg = 2.5/8 = 0.3125 — diff = 0.0−0.3125 = −0.3125 < −0.15
        let deadlineTag = Tag(name: "deadlines", colorHex: "#FF0000", isAutoGenerated: false)
        let neutralEntries = (0..<5).map { _ in makeEntry(mood: .neutral) }
        let badEntries = (0..<3).map { _ in makeEntry(mood: .terrible, tags: [deadlineTag]) }
        let insights = InsightEngine.generateInsights(from: neutralEntries + badEntries)
        XCTAssertTrue(insights.contains { $0.type == .tagMoodCorrelation },
                      "Should detect negative tag-mood correlation when a tag strongly predicts worse mood")
    }

    func testTagWithFewerThanThreeEntriesIgnored() {
        // 5 neutral (no tag) + 2 great with "exercise" tag — only 2 occurrences, below the 3-entry threshold
        let exerciseTag = Tag(name: "exercise", colorHex: "#00FF00", isAutoGenerated: false)
        let neutralEntries = (0..<5).map { _ in makeEntry(mood: .neutral) }
        let taggedEntries = (0..<2).map { _ in makeEntry(mood: .great, tags: [exerciseTag]) }
        let insights = InsightEngine.generateInsights(from: neutralEntries + taggedEntries)
        XCTAssertFalse(insights.contains { $0.type == .tagMoodCorrelation },
                       "Tag with fewer than 3 entries should be excluded from mood correlation analysis")
    }

    // MARK: - Best Day of Week

    func testBestDayOfWeekDetected() {
        // Group 1 (today's weekday: 0, 7, 14 days ago): great mood → avg 1.0
        // Group 2 (same weekday −3 days: 3, 10, 17 days ago): terrible mood → avg 0.0
        // Group 3 (same weekday −6 days: 6, 13, 20 days ago): neutral mood → avg 0.5
        // 3 distinct weekdays, diff 1.0−0.0 = 1.0 > 0.1 → timePattern
        let greatEntries  = [0, 7, 14].map { n in makeEntry(mood: .great,   createdAt: daysAgo(n)) }
        let worstEntries  = [3, 10, 17].map { n in makeEntry(mood: .terrible, createdAt: daysAgo(n)) }
        let neutralEntries = [6, 13, 20].map { n in makeEntry(mood: .neutral, createdAt: daysAgo(n)) }
        let insights = InsightEngine.generateInsights(from: greatEntries + worstEntries + neutralEntries)
        XCTAssertTrue(insights.contains { $0.type == .timePattern },
                      "Should detect best day of week when one weekday consistently has better mood")
    }

    func testBestDayOfWeekNoInsightWhenVarianceTooSmall() {
        // 15 consecutive days, all neutral (0.5) — all weekday averages identical, diff ≤ 0.1 → nil
        let entries = (0..<15).map { i in makeEntry(mood: .neutral, createdAt: daysAgo(i)) }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertFalse(insights.contains { $0.type == .timePattern },
                       "Should not produce a timePattern insight when mood variance across weekdays is below threshold")
    }

    // MARK: - Writing Time Pattern

    func testMorningWritingPattern() {
        // 8 entries at 09:00 + 2 at 14:00 → morningCount=8, ratio=0.8 > 0.5 → writingHabit
        let morningEntries  = (0..<8).map { i in makeEntry(createdAt: dateWithHour(9,  daysAgo: i)) }
        let afternoonEntries = (0..<2).map { i in makeEntry(createdAt: dateWithHour(14, daysAgo: i + 8)) }
        let insights = InsightEngine.generateInsights(from: morningEntries + afternoonEntries)
        XCTAssertTrue(insights.contains { $0.type == .writingHabit },
                      "Should detect morning writing pattern when >50% of entries are written before noon")
    }

    func testEveningWritingPattern() {
        // 8 entries at 22:00 + 2 at 09:00 → eveningCount=8, ratio=0.8 > 0.5 → writingHabit
        let eveningEntries = (0..<8).map { i in makeEntry(createdAt: dateWithHour(22, daysAgo: i)) }
        let morningEntries = (0..<2).map { i in makeEntry(createdAt: dateWithHour(9,  daysAgo: i + 8)) }
        let insights = InsightEngine.generateInsights(from: eveningEntries + morningEntries)
        XCTAssertTrue(insights.contains { $0.type == .writingHabit },
                      "Should detect evening writing pattern when >50% of entries are written in the evening")
    }

    func testWritingTimePatternRequiresSevenOrMoreEntries() {
        // 6 morning entries (no mood) — total=6 < 7 guard → writingTimePattern returns nil
        // Nil mood prevents tagMoodCorrelation, bestDayOfWeek, and wordCountMoodCorrelation from firing
        let entries = (0..<6).map { i in makeEntry(createdAt: dateWithHour(9, daysAgo: i)) }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertFalse(insights.contains { $0.type == .writingHabit },
                       "writingTimePattern should not fire when fewer than 7 entries are present")
    }

    func testAfternoonWritingPattern() {
        // 8 entries at 14:00 (afternoon, 12–17) + 2 at 09:00 (morning)
        // afternoonCount=8, total=10, ratio=0.8 > 0.5 → writingHabit insight
        let afternoonEntries = (0..<8).map { i in makeEntry(createdAt: dateWithHour(14, daysAgo: i)) }
        let morningEntries   = (0..<2).map { i in makeEntry(createdAt: dateWithHour(9,  daysAgo: i + 8)) }
        let insights = InsightEngine.generateInsights(from: afternoonEntries + morningEntries)
        XCTAssertTrue(insights.contains { $0.type == .writingHabit },
                      "Should detect afternoon writing pattern when >50% of entries are written in the afternoon")
    }

    // MARK: - Word Count Mood Correlation Guards

    func testWordCountMoodCorrelationRequiresTenEntries() {
        // 9 entries with mood+wordcount: below the ≥10 threshold → wordCountMoodCorrelation returns nil
        // Hours distributed 3+3+3 so writingTimePattern ratio ≤ 0.5 also doesn't fire
        let hours = [9, 14, 22, 9, 14, 22, 9, 14, 22]
        let entries = (0..<9).map { i in
            makeEntry(content: "one two three", mood: .good, createdAt: dateWithHour(hours[i], daysAgo: i))
        }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertFalse(insights.contains { $0.type == .writingHabit },
                       "wordCountMoodCorrelation should not fire with fewer than 10 entries")
    }

    func testWordCountMoodCorrelationDiffTooSmall() {
        // 12 entries: 6 short + 6 long, all Mood.neutral — both halves avg 0.5, diff = 0 ≤ 0.1 → nil
        // Hours: 4 morning + 4 afternoon + 4 evening → ratio = 4/12 ≤ 0.5 so writingTimePattern won't fire
        // 12 distinct days (daysAgo 0–11) → uniqueDays=12, not ≤5 so consistencyInsight won't fire
        let shortContent = "brief"
        let longContent = "one two three four five six seven eight nine ten"
        let hours = [9, 14, 22, 9, 14, 22, 9, 14, 22, 9, 14, 22]
        let entries =
            (0..<6).map { i in makeEntry(content: shortContent, mood: .neutral, createdAt: dateWithHour(hours[i],     daysAgo: i)) } +
            (0..<6).map { i in makeEntry(content: longContent,  mood: .neutral, createdAt: dateWithHour(hours[i + 6], daysAgo: i + 6)) }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertFalse(insights.contains { $0.type == .writingHabit },
                       "wordCountMoodCorrelation should not fire when long vs short entry mood diff is ≤ 0.1")
    }

    // MARK: - Best Day of Week Guard

    func testBestDayOfWeekRequiresThreeWeekdays() {
        // Entries spaced exactly 7 days apart → all land on the same weekday
        // dayMoods.count = 1 < 3 guard → bestDayOfWeek returns nil
        // total = 5 < 7 so writingTimePattern also won't fire
        let entries = [0, 7, 14, 21, 28].map { n in makeEntry(mood: .great, createdAt: daysAgo(n)) }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertFalse(insights.contains { $0.type == .timePattern },
                       "bestDayOfWeek should not fire when entries span fewer than 3 distinct weekdays")
    }

    // MARK: - Minimum Entry Threshold

    func testNoInsightsWithSixEntries() {
        // 6 < 7 minimum → generateInsights returns [] immediately
        let entries = (0..<6).map { _ in makeEntry(mood: .good) }
        let insights = InsightEngine.generateInsights(from: entries)
        XCTAssertTrue(insights.isEmpty, "6 entries is below the 7-entry minimum threshold")
    }

    // MARK: - Tag Mood Correlation Cap

    func testTagMoodCorrelationCappedAtTwo() {
        // 3 tags each with 3 great-mood entries → all qualify (diff > 0.15 vs overall avg)
        // tagMoodCorrelations caps results at 2; total tagMoodCorrelation insights must be ≤ 2
        let alphaTag = Tag(name: "alpha", colorHex: "FF0000", isAutoGenerated: true)
        let betaTag  = Tag(name: "beta",  colorHex: "00FF00", isAutoGenerated: true)
        let gammaTag = Tag(name: "gamma", colorHex: "0000FF", isAutoGenerated: true)

        // 3 entries per tag with .great mood (normalizedValue = 1.0)
        let taggedEntries = (0..<3).flatMap { i -> [JournalEntry] in [
            makeEntry(mood: .great, createdAt: daysAgo(i),      tags: [alphaTag]),
            makeEntry(mood: .great, createdAt: daysAgo(i + 3),  tags: [betaTag]),
            makeEntry(mood: .great, createdAt: daysAgo(i + 6),  tags: [gammaTag]),
        ]}
        // 7 neutral-mood entries with no tags to bring overall average down
        let neutralEntries = (0..<7).map { i in makeEntry(mood: .neutral, createdAt: daysAgo(i + 9)) }

        let allEntries = taggedEntries + neutralEntries  // 16 entries ≥ 7
        let insights = InsightEngine.generateInsights(from: allEntries)
        let tagInsights = insights.filter { $0.type == .tagMoodCorrelation }

        XCTAssertLessThanOrEqual(tagInsights.count, 2,
                                 "tagMoodCorrelations should return at most 2 insights even when 3+ tags qualify")
    }
}
