import XCTest
@testable import Kinen

final class JournalEntryTests: XCTestCase {

    // MARK: - Init

    func testInitDefaultValues() {
        let entry = JournalEntry(content: "Hello world")
        XCTAssertEqual(entry.content, "Hello world")
        XCTAssertNil(entry.title)
        XCTAssertNil(entry.mood)
        XCTAssertNil(entry.template)
        XCTAssertEqual(entry.wordCount, 2)
        XCTAssertFalse(entry.isBookmarked)
        XCTAssertFalse(entry.isHidden)
        XCTAssertFalse(entry.isPinned)
        XCTAssertNil(entry.previousContent)
        XCTAssertEqual(entry.writingDuration, 0)
        XCTAssertEqual(entry.safeTags.count, 0)
        XCTAssertEqual(entry.safeInsights.count, 0)
    }

    func testInitWithMoodAndTitle() {
        let entry = JournalEntry(content: "Great day", title: "My Day", mood: .great)
        XCTAssertEqual(entry.title, "My Day")
        XCTAssertEqual(entry.mood, .great)
        XCTAssertEqual(entry.displayTitle, "My Day")
    }

    func testWordCount() {
        let entry = JournalEntry(content: "one two three four five")
        XCTAssertEqual(entry.wordCount, 5)
    }

    func testEmptyContent() {
        let entry = JournalEntry(content: "")
        XCTAssertEqual(entry.wordCount, 0)
    }

    // MARK: - Display Title

    func testDisplayTitleFallsBackToDate() {
        let entry = JournalEntry(content: "test")
        // No title set → should use date formatter
        XCTAssertFalse(entry.displayTitle.isEmpty)
    }

    func testDisplayTitleUsesTitle() {
        let entry = JournalEntry(content: "test", title: "My Title")
        XCTAssertEqual(entry.displayTitle, "My Title")
    }

    func testDisplayTitleIgnoresEmptyTitle() {
        let entry = JournalEntry(content: "test", title: "")
        // Empty title → should fall back to date
        XCTAssertNotEqual(entry.displayTitle, "")
    }

    // MARK: - Preview

    func testPreviewShortContent() {
        let entry = JournalEntry(content: "Short text")
        XCTAssertEqual(entry.preview, "Short text")
    }

    func testPreviewLongContent() {
        let longText = String(repeating: "a", count: 150)
        let entry = JournalEntry(content: longText)
        XCTAssertTrue(entry.preview.hasSuffix("..."))
        XCTAssertEqual(entry.preview.count, 103) // 100 chars + "..."
    }

    func testPreviewMultiline() {
        let entry = JournalEntry(content: "First line\nSecond line\nThird line")
        XCTAssertEqual(entry.preview, "First line")
    }

    // MARK: - Tags

    func testAddTagToNilArray() {
        let entry = JournalEntry(content: "test")
        entry.tags = nil
        let tag = Tag(name: "test-tag", colorHex: "FF0000", isAutoGenerated: false)
        entry.addTag(tag)
        XCTAssertEqual(entry.safeTags.count, 1)
        XCTAssertEqual(entry.safeTags.first?.name, "test-tag")
    }

    func testAddTagToExistingArray() {
        let entry = JournalEntry(content: "test")
        let tag1 = Tag(name: "first", colorHex: "FF0000", isAutoGenerated: false)
        let tag2 = Tag(name: "second", colorHex: "00FF00", isAutoGenerated: false)
        entry.addTag(tag1)
        entry.addTag(tag2)
        XCTAssertEqual(entry.safeTags.count, 2)
    }

    // MARK: - Insights

    func testAddInsightToNilArray() {
        let entry = JournalEntry(content: "test")
        entry.insights = nil
        let insight = EntryInsight(type: .sentiment, content: "Positive!")
        entry.addInsight(insight)
        XCTAssertEqual(entry.safeInsights.count, 1)
    }

    func testAddInsightToExistingArray() {
        let entry = JournalEntry(content: "test")
        let insight1 = EntryInsight(type: .sentiment, content: "Positive vibes")
        let insight2 = EntryInsight(type: .suggestion, content: "Try journaling more")
        entry.addInsight(insight1)
        entry.addInsight(insight2)
        XCTAssertEqual(entry.safeInsights.count, 2)
        XCTAssertEqual(entry.safeInsights[0].content, "Positive vibes")
        XCTAssertEqual(entry.safeInsights[1].content, "Try journaling more")
    }

    // MARK: - Snapshot / Undo

    func testSnapshotForUndo() {
        let entry = JournalEntry(content: "Original content")
        XCTAssertNil(entry.previousContent)

        entry.snapshotForUndo()
        XCTAssertEqual(entry.previousContent, "Original content")

        entry.content = "Updated content"
        XCTAssertEqual(entry.previousContent, "Original content")
    }

    func testSnapshotPreservesOldContent() {
        let entry = JournalEntry(content: "Version 1")
        entry.snapshotForUndo()
        entry.content = "Version 2"
        entry.snapshotForUndo()
        entry.content = "Version 3"

        // Only stores one previous version
        XCTAssertEqual(entry.previousContent, "Version 2")
    }

    // MARK: - Pinning

    func testPinnedDefault() {
        let entry = JournalEntry(content: "test")
        XCTAssertFalse(entry.isPinned)
    }

    func testPinToggle() {
        let entry = JournalEntry(content: "test")
        entry.isPinned = true
        XCTAssertTrue(entry.isPinned)
        entry.isPinned = false
        XCTAssertFalse(entry.isPinned)
    }
}
