import XCTest
@testable import Kinen

final class TagTests: XCTestCase {

    // MARK: - init: name normalization

    func testInitLowercasesName() {
        let tag = Tag(name: "Hello World")
        XCTAssertEqual(tag.name, "hello world")
    }

    func testInitTrimsLeadingTrailingWhitespace() {
        let tag = Tag(name: "  diary  ")
        XCTAssertEqual(tag.name, "diary")
    }

    func testInitTrimsAndLowercases() {
        let tag = Tag(name: "  Travel Notes  ")
        XCTAssertEqual(tag.name, "travel notes")
    }

    func testInitEmptyNameStaysEmpty() {
        let tag = Tag(name: "")
        XCTAssertEqual(tag.name, "")
    }

    func testInitCJKNamePreserved() {
        let tag = Tag(name: "旅行")
        XCTAssertEqual(tag.name, "旅行")
    }

    func testInitAlreadyLowercaseUnchanged() {
        let tag = Tag(name: "work")
        XCTAssertEqual(tag.name, "work")
    }

    // MARK: - init: default values

    func testInitDefaultColorHex() {
        let tag = Tag(name: "test")
        XCTAssertEqual(tag.colorHex, "8B5CF6")
    }

    func testInitDefaultIsAutoGeneratedFalse() {
        let tag = Tag(name: "test")
        XCTAssertFalse(tag.isAutoGenerated)
    }

    func testInitCustomColorHex() {
        let tag = Tag(name: "work", colorHex: "FF0000")
        XCTAssertEqual(tag.colorHex, "FF0000")
    }

    func testInitIsAutoGeneratedTrue() {
        let tag = Tag(name: "ai-tag", isAutoGenerated: true)
        XCTAssertTrue(tag.isAutoGenerated)
    }

    // MARK: - id uniqueness

    func testEachTagGetsUniqueId() {
        let a = Tag(name: "alpha")
        let b = Tag(name: "beta")
        XCTAssertNotEqual(a.id, b.id)
    }

    // MARK: - safeEntries / entryCount

    func testSafeEntriesReturnsEmptyWhenNil() {
        let tag = Tag(name: "test")
        tag.entries = nil
        XCTAssertTrue(tag.safeEntries.isEmpty)
    }

    func testSafeEntriesDefaultEmptyFromInit() {
        let tag = Tag(name: "test")
        XCTAssertTrue(tag.safeEntries.isEmpty)
    }

    func testEntryCountZeroWhenNil() {
        let tag = Tag(name: "test")
        tag.entries = nil
        XCTAssertEqual(tag.entryCount, 0)
    }

    func testEntryCountZeroFromInit() {
        let tag = Tag(name: "test")
        XCTAssertEqual(tag.entryCount, 0)
    }

    // MARK: - createdAt

    func testCreatedAtIsRecent() {
        let tag = Tag(name: "test")
        XCTAssertLessThan(abs(tag.createdAt.timeIntervalSinceNow), 5)
    }
}

// MARK: -

final class EntryInsightTests: XCTestCase {

    func testInitStoresType() {
        let insight = EntryInsight(type: .sentiment, content: "Positive vibe")
        XCTAssertEqual(insight.type, .sentiment)
    }

    func testInitStoresContent() {
        let insight = EntryInsight(type: .pattern, content: "Weekly pattern detected")
        XCTAssertEqual(insight.content, "Weekly pattern detected")
    }

    func testInitSetsUniqueId() {
        let a = EntryInsight(type: .streak, content: "A")
        let b = EntryInsight(type: .streak, content: "B")
        XCTAssertNotEqual(a.id, b.id)
    }

    func testInitCreatedAtIsRecent() {
        let insight = EntryInsight(type: .suggestion, content: "Try meditating")
        XCTAssertLessThan(abs(insight.createdAt.timeIntervalSinceNow), 5)
    }

    func testAllInsightTypesStoredCorrectly() {
        let types: [InsightType] = [.sentiment, .pattern, .suggestion, .topicExtraction, .streak]
        for t in types {
            let insight = EntryInsight(type: t, content: "x")
            XCTAssertEqual(insight.type, t)
        }
    }
}
