import Foundation
import SwiftData
import CryptoKit
import CommonCrypto
import OSLog
#if canImport(UIKit)
import UIKit
#endif

private let logger = Logger(subsystem: "com.jasonye.kinen", category: "Backup")

/// Encrypted backup and restore service.
/// Creates .kinenbackup files (AES-256-GCM encrypted JSON).
struct BackupService {

    struct BackupMetadata: Codable {
        let version: String
        let createdAt: Date
        let entryCount: Int
        let deviceName: String
    }

    struct BackupData: Codable {
        let metadata: BackupMetadata
        let entries: [BackupEntry]
        let tags: [BackupTag]
    }

    struct BackupEntry: Codable {
        let id: String
        let content: String
        let title: String?
        let createdAt: Date
        let updatedAt: Date
        let mood: Int?
        let sentimentScore: Double?
        let wordCount: Int
        let isBookmarked: Bool
        let writingDuration: TimeInterval
        let tagNames: [String]
        let insights: [BackupInsight]
    }

    struct BackupInsight: Codable {
        let type: String
        let content: String
        let createdAt: Date
    }

    struct BackupTag: Codable {
        let name: String
        let colorHex: String
        let isAutoGenerated: Bool
    }

    // MARK: - Create Backup

    static func createBackup(entries: [JournalEntry], tags: [Tag], password: String) throws -> Data {
        // Build backup data
        let backupEntries = entries.map { entry in
            BackupEntry(
                id: entry.id.uuidString,
                content: entry.content,
                title: entry.title,
                createdAt: entry.createdAt,
                updatedAt: entry.updatedAt,
                mood: entry.mood?.rawValue,
                sentimentScore: entry.sentimentScore,
                wordCount: entry.wordCount,
                isBookmarked: entry.isBookmarked,
                writingDuration: entry.writingDuration,
                tagNames: entry.safeTags.map(\.name),
                insights: entry.safeInsights.map {
                    BackupInsight(type: $0.type.rawValue, content: $0.content, createdAt: $0.createdAt)
                }
            )
        }

        let backupTags = tags.map {
            BackupTag(name: $0.name, colorHex: $0.colorHex, isAutoGenerated: $0.isAutoGenerated)
        }

        #if os(macOS)
        let deviceName = Host.current().localizedName ?? "Mac"
        #elseif canImport(UIKit)
        let deviceName = UIDevice.current.name
        #else
        let deviceName = "Unknown"
        #endif

        let backup = BackupData(
            metadata: BackupMetadata(
                version: "1.0",
                createdAt: Date(),
                entryCount: entries.count,
                deviceName: deviceName
            ),
            entries: backupEntries,
            tags: backupTags
        )

        // Serialize to JSON
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let jsonData = try encoder.encode(backup)

        // Encrypt with AES-256-GCM
        let encrypted = try encrypt(data: jsonData, password: password)
        logger.info("Backup created: \(entries.count) entries, \(encrypted.count) bytes encrypted")
        return encrypted
    }

    // MARK: - Preview Backup

    struct BackupPreview {
        let entryCount: Int
        let tagCount: Int
        let deviceName: String
        let createdAt: Date
    }

    /// Decrypt and inspect a backup without importing. Returns metadata for user confirmation.
    static func previewBackup(data: Data, password: String) throws -> BackupPreview {
        let jsonData = try decrypt(data: data, password: password)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let backup = try decoder.decode(BackupData.self, from: jsonData)
        return BackupPreview(
            entryCount: backup.entries.count,
            tagCount: backup.tags.count,
            deviceName: backup.metadata.deviceName,
            createdAt: backup.metadata.createdAt
        )
    }

    // MARK: - Restore Backup

    static func restoreBackup(data: Data, password: String, context: ModelContext) throws -> Int {
        // Decrypt
        let jsonData = try decrypt(data: data, password: password)

        // Deserialize
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let backup = try decoder.decode(BackupData.self, from: jsonData)

        var importedCount = 0

        // Import tags first
        for backupTag in backup.tags {
            let descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == backupTag.name })
            let existing = (try? context.fetch(descriptor)) ?? []
            if existing.isEmpty {
                let tag = Tag(name: backupTag.name, colorHex: backupTag.colorHex, isAutoGenerated: backupTag.isAutoGenerated)
                context.insert(tag)
            }
        }

        // Import entries (skip duplicates by UUID)
        for backupEntry in backup.entries {
            guard let uuid = UUID(uuidString: backupEntry.id) else { continue }
            let descriptor = FetchDescriptor<JournalEntry>(predicate: #Predicate { $0.id == uuid })
            let existing = (try? context.fetch(descriptor)) ?? []

            if existing.isEmpty {
                let entry = JournalEntry(
                    content: backupEntry.content,
                    title: backupEntry.title,
                    mood: backupEntry.mood.flatMap { Mood(rawValue: $0) },
                    createdAt: backupEntry.createdAt
                )
                entry.id = uuid
                entry.updatedAt = backupEntry.updatedAt
                entry.sentimentScore = backupEntry.sentimentScore
                entry.wordCount = backupEntry.wordCount
                entry.isBookmarked = backupEntry.isBookmarked
                entry.writingDuration = backupEntry.writingDuration
                context.insert(entry)

                // Restore tag relationships
                for tagName in backupEntry.tagNames {
                    let tagDescriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == tagName })
                    if let tag = (try? context.fetch(tagDescriptor))?.first {
                        entry.addTag(tag)
                    }
                }

                // Restore insights
                for backupInsight in backupEntry.insights {
                    if let type = InsightType(rawValue: backupInsight.type) {
                        let insight = EntryInsight(type: type, content: backupInsight.content)
                        insight.createdAt = backupInsight.createdAt
                        entry.addInsight(insight)
                    }
                }

                importedCount += 1
            }
        }

        logger.info("Restored \(importedCount) entries from backup (total in backup: \(backup.entries.count))")
        return importedCount
    }

    // MARK: - AES-256-GCM Encryption

    private static let saltLength = 16
    private static let pbkdf2Rounds: UInt32 = 100_000

    private static func encrypt(data: Data, password: String) throws -> Data {
        var salt = Data(count: saltLength)
        let result = salt.withUnsafeMutableBytes { SecRandomCopyBytes(kSecRandomDefault, saltLength, $0.baseAddress!) }
        guard result == errSecSuccess else { throw BackupError.encryptionFailed }

        let key = try deriveKey(password: password, salt: salt)
        let sealedBox = try AES.GCM.seal(data, using: key)
        guard let combined = sealedBox.combined else {
            throw BackupError.encryptionFailed
        }
        // Format: [salt (16 bytes)] + [AES-GCM sealed box]
        return salt + combined
    }

    private static func decrypt(data: Data, password: String) throws -> Data {
        guard data.count > saltLength else { throw BackupError.corruptedData }

        let salt = data.prefix(saltLength)
        let encrypted = data.dropFirst(saltLength)

        let key = try deriveKey(password: password, salt: salt)
        let sealedBox = try AES.GCM.SealedBox(combined: encrypted)
        return try AES.GCM.open(sealedBox, using: key)
    }

    /// Derive a 256-bit key from password using PBKDF2-HMAC-SHA256.
    private static func deriveKey(password: String, salt: Data) throws -> SymmetricKey {
        let passwordData = Data(password.utf8)
        var derivedKey = Data(count: 32) // 256 bits

        let status = derivedKey.withUnsafeMutableBytes { derivedKeyBytes in
            salt.withUnsafeBytes { saltBytes in
                passwordData.withUnsafeBytes { passwordBytes in
                    CCKeyDerivationPBKDF(
                        CCPBKDFAlgorithm(kCCPBKDF2),
                        passwordBytes.baseAddress?.assumingMemoryBound(to: Int8.self),
                        passwordData.count,
                        saltBytes.baseAddress?.assumingMemoryBound(to: UInt8.self),
                        salt.count,
                        CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA256),
                        pbkdf2Rounds,
                        derivedKeyBytes.baseAddress?.assumingMemoryBound(to: UInt8.self),
                        32
                    )
                }
            }
        }

        guard status == kCCSuccess else { throw BackupError.encryptionFailed }
        return SymmetricKey(data: derivedKey)
    }
}

enum BackupError: LocalizedError {
    case encryptionFailed
    case decryptionFailed
    case invalidPassword
    case corruptedData

    var errorDescription: String? {
        switch self {
        case .encryptionFailed: "Failed to encrypt backup data"
        case .decryptionFailed: "Failed to decrypt backup. Check your password."
        case .invalidPassword: "Incorrect password"
        case .corruptedData: "Backup file is corrupted or invalid"
        }
    }
}
