import Foundation
import SwiftData
import CryptoKit
import OSLog
#if canImport(UIKit)
import UIKit
#endif

private let logger = Logger(subsystem: "com.kinen.app", category: "Backup")

/// Encrypted backup and restore service.
/// Creates .kinenbackup files (AES-256-GCM encrypted JSON).
struct BackupService {

    struct BackupMetadata: Codable {
        let version: String
        let createdAt: Date
        let entryCount: Int
        let deviceName: String
    }

    struct BackupData: Codable {
        let metadata: BackupMetadata
        let entries: [BackupEntry]
        let tags: [BackupTag]
    }

    struct BackupEntry: Codable {
        let id: String
        let content: String
        let title: String?
        let createdAt: Date
        let updatedAt: Date
        let mood: Int?
        let sentimentScore: Double?
        let wordCount: Int
        let isBookmarked: Bool
        let writingDuration: TimeInterval
        let tagNames: [String]
        let insights: [BackupInsight]
    }

    struct BackupInsight: Codable {
        let type: String
        let content: String
        let createdAt: Date
    }

    struct BackupTag: Codable {
        let name: String
        let colorHex: String
        let isAutoGenerated: Bool
    }

    // MARK: - Create Backup

    static func createBackup(entries: [JournalEntry], tags: [Tag], password: String) throws -> Data {
        // Build backup data
        let backupEntries = entries.map { entry in
            BackupEntry(
                id: entry.id.uuidString,
                content: entry.content,
                title: entry.title,
                createdAt: entry.createdAt,
                updatedAt: entry.updatedAt,
                mood: entry.mood?.rawValue,
                sentimentScore: entry.sentimentScore,
                wordCount: entry.wordCount,
                isBookmarked: entry.isBookmarked,
                writingDuration: entry.writingDuration,
                tagNames: entry.safeTags.map(\.name),
                insights: entry.safeInsights.map {
                    BackupInsight(type: $0.type.rawValue, content: $0.content, createdAt: $0.createdAt)
                }
            )
        }

        let backupTags = tags.map {
            BackupTag(name: $0.name, colorHex: $0.colorHex, isAutoGenerated: $0.isAutoGenerated)
        }

        #if os(macOS)
        let deviceName = Host.current().localizedName ?? "Mac"
        #elseif canImport(UIKit)
        let deviceName = UIDevice.current.name
        #else
        let deviceName = "Unknown"
        #endif

        let backup = BackupData(
            metadata: BackupMetadata(
                version: "1.0",
                createdAt: Date(),
                entryCount: entries.count,
                deviceName: deviceName
            ),
            entries: backupEntries,
            tags: backupTags
        )

        // Serialize to JSON
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let jsonData = try encoder.encode(backup)

        // Encrypt with AES-256-GCM
        let encrypted = try encrypt(data: jsonData, password: password)
        logger.info("Backup created: \(entries.count) entries, \(encrypted.count) bytes encrypted")
        return encrypted
    }

    // MARK: - Restore Backup

    static func restoreBackup(data: Data, password: String, context: ModelContext) throws -> Int {
        // Decrypt
        let jsonData = try decrypt(data: data, password: password)

        // Deserialize
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let backup = try decoder.decode(BackupData.self, from: jsonData)

        var importedCount = 0

        // Import tags first
        for backupTag in backup.tags {
            let descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == backupTag.name })
            let existing = (try? context.fetch(descriptor)) ?? []
            if existing.isEmpty {
                let tag = Tag(name: backupTag.name, colorHex: backupTag.colorHex, isAutoGenerated: backupTag.isAutoGenerated)
                context.insert(tag)
            }
        }

        // Import entries (skip duplicates by UUID)
        for backupEntry in backup.entries {
            guard let uuid = UUID(uuidString: backupEntry.id) else { continue }
            let descriptor = FetchDescriptor<JournalEntry>(predicate: #Predicate { $0.id == uuid })
            let existing = (try? context.fetch(descriptor)) ?? []

            if existing.isEmpty {
                let entry = JournalEntry(
                    content: backupEntry.content,
                    title: backupEntry.title,
                    mood: backupEntry.mood.flatMap { Mood(rawValue: $0) },
                    createdAt: backupEntry.createdAt
                )
                entry.id = uuid
                entry.updatedAt = backupEntry.updatedAt
                entry.sentimentScore = backupEntry.sentimentScore
                entry.wordCount = backupEntry.wordCount
                entry.isBookmarked = backupEntry.isBookmarked
                entry.writingDuration = backupEntry.writingDuration
                context.insert(entry)
                importedCount += 1
            }
        }

        logger.info("Restored \(importedCount) entries from backup (total in backup: \(backup.entries.count))")
        return importedCount
    }

    // MARK: - AES-256-GCM Encryption

    private static func encrypt(data: Data, password: String) throws -> Data {
        let key = deriveKey(password: password)
        let sealedBox = try AES.GCM.seal(data, using: key)
        guard let combined = sealedBox.combined else {
            throw BackupError.encryptionFailed
        }
        return combined
    }

    private static func decrypt(data: Data, password: String) throws -> Data {
        let key = deriveKey(password: password)
        let sealedBox = try AES.GCM.SealedBox(combined: data)
        return try AES.GCM.open(sealedBox, using: key)
    }

    /// Derive a 256-bit key from password using SHA256.
    /// In production, use PBKDF2 or Argon2 for stronger key derivation.
    private static func deriveKey(password: String) -> SymmetricKey {
        let hash = SHA256.hash(data: Data(password.utf8))
        return SymmetricKey(data: hash)
    }
}

enum BackupError: LocalizedError {
    case encryptionFailed
    case decryptionFailed
    case invalidPassword
    case corruptedData

    var errorDescription: String? {
        switch self {
        case .encryptionFailed: "Failed to encrypt backup data"
        case .decryptionFailed: "Failed to decrypt backup. Check your password."
        case .invalidPassword: "Incorrect password"
        case .corruptedData: "Backup file is corrupted or invalid"
        }
    }
}
