import Foundation
import SwiftData
import OSLog

private let logger = Logger(subsystem: "com.jasonye.kinen", category: "SampleDataLoader")

/// Inserts a realistic, feature-rich sample journal so a first-launch user (or
/// an App Review reviewer) can see every screen populated. All entries carry
/// `isSampleData == true` so they can be cleared in one tap and never co-mingle
/// with a real user's notebook.
///
/// Sample entries display only a plain string in the `weather` field; the Apple
/// Weather attribution is shown only by `WeatherAttributionView` for live
/// `WeatherAttribution` objects, never for sample entries.
@MainActor
struct SampleDataLoader {
    static let entryCount = 30

    /// Inserts `entryCount` realistic sample journal entries. Idempotent: if any
    /// `isSampleData == true` entry is already present, this is a no-op and
    /// returns 0.
    @discardableResult
    static func loadSampleEntries(into context: ModelContext) -> Int {
        if sampleEntryCount(in: context) > 0 {
            return 0
        }

        let tagPool = makeTagPool(in: context)
        let calendar = Calendar.current
        let now = Date()
        var inserted = 0
        let plan = entryPlan()

        for (index, blueprint) in plan.enumerated() {
            guard let createdAt = calendar.date(byAdding: .day, value: -blueprint.daysAgo, to: now) else { continue }
            let scheduled = calendar.date(bySettingHour: blueprint.hour, minute: blueprint.minute, second: 0, of: createdAt) ?? createdAt

            let entry = JournalEntry(
                content: blueprint.content,
                title: blueprint.title,
                mood: blueprint.mood,
                template: blueprint.template,
                createdAt: scheduled
            )
            entry.isSampleData = true
            entry.weather = blueprint.weather
            entry.location = blueprint.location.name
            entry.latitude = blueprint.location.latitude
            entry.longitude = blueprint.location.longitude
            entry.wordCount = blueprint.content.split(whereSeparator: { $0.isWhitespace }).count
            entry.writingDuration = blueprint.writingDuration
            entry.isPinned = (index == 4)            // exactly 1 pinned
            entry.isBookmarked = [2, 11, 22].contains(index)  // 3 bookmarked
            entry.sentimentScore = blueprint.sentiment

            for tagName in blueprint.tags {
                if let tag = tagPool[tagName] {
                    entry.addTag(tag)
                }
            }

            for insightSpec in blueprint.insights {
                let insight = EntryInsight(type: insightSpec.type, content: insightSpec.content)
                entry.addInsight(insight)
            }

            context.insert(entry)
            inserted += 1
        }

        do {
            try context.save()
        } catch {
            logger.error("SampleDataLoader save failed: \(error)")
        }
        return inserted
    }

    /// Removes every entry where `isSampleData == true`. Sample-only tags become
    /// orphaned (no entries) and are removed too. Real user entries and any tags
    /// they reference are left untouched.
    @discardableResult
    static func clearSampleEntries(from context: ModelContext) -> Int {
        let descriptor = FetchDescriptor<JournalEntry>(predicate: #Predicate { $0.isSampleData == true })
        let entries: [JournalEntry]
        do {
            entries = try context.fetch(descriptor)
        } catch {
            logger.error("clearSampleEntries fetch failed: \(error)")
            return 0
        }
        let removed = entries.count
        for entry in entries {
            context.delete(entry)
        }

        // Remove sample-pool tags that became orphaned after the deletion. We
        // only consider auto-generated tags whose name is in the curated pool,
        // and only delete them if their entry list is empty after the deletion.
        let sampleTagNames = Set(curatedTagNames)
        let tagDescriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.isAutoGenerated == true })
        if let tags = try? context.fetch(tagDescriptor) {
            for tag in tags where sampleTagNames.contains(tag.name) {
                if tag.safeEntries.isEmpty {
                    context.delete(tag)
                }
            }
        }

        do {
            try context.save()
        } catch {
            logger.error("clearSampleEntries save failed: \(error)")
        }
        return removed
    }

    /// Returns the number of entries with `isSampleData == true` in the context.
    static func sampleEntryCount(in context: ModelContext) -> Int {
        let descriptor = FetchDescriptor<JournalEntry>(predicate: #Predicate { $0.isSampleData == true })
        return (try? context.fetchCount(descriptor)) ?? 0
    }

    // MARK: - Tag pool

    private static let curatedTagNames: [String] = [
        "work", "family", "gratitude", "morning", "evening",
        "exercise", "creative", "reflection", "travel", "sleep",
        "goals", "mindfulness"
    ]

    private static func makeTagPool(in context: ModelContext) -> [String: Tag] {
        var pool: [String: Tag] = [:]
        for raw in curatedTagNames {
            let name = raw.lowercased()
            let descriptor = FetchDescriptor<Tag>(predicate: #Predicate { $0.name == name })
            if let existing = (try? context.fetch(descriptor))?.first {
                pool[raw] = existing
            } else {
                let tag = Tag(name: raw, isAutoGenerated: true)
                context.insert(tag)
                pool[raw] = tag
            }
        }
        return pool
    }

    // MARK: - Plan

    private struct Blueprint {
        let daysAgo: Int
        let hour: Int
        let minute: Int
        let title: String?
        let content: String
        let mood: Mood
        let template: JournalTemplate?
        let weather: String
        let location: SampleLocation
        let tags: [String]
        let insights: [InsightSpec]
        let writingDuration: TimeInterval
        let sentiment: Double
    }

    private struct InsightSpec {
        let type: InsightType
        let content: String
    }

    private struct SampleLocation {
        let name: String
        let latitude: Double
        let longitude: Double
    }

    private static let sf  = SampleLocation(name: "San Francisco, CA", latitude: 37.7749, longitude: -122.4194)
    private static let nyc = SampleLocation(name: "New York, NY",      latitude: 40.7128, longitude: -74.0060)
    private static let tyo = SampleLocation(name: "Tokyo, Japan",      latitude: 35.6762, longitude: 139.6503)
    private static let sea = SampleLocation(name: "Seattle, WA",       latitude: 47.6062, longitude: -122.3321)
    private static let lis = SampleLocation(name: "Lisbon, Portugal",  latitude: 38.7223, longitude: -9.1393)

    private static let weatherSunny       = "☀️ Sunny, 72°F"
    private static let weatherPartlyCloud = "⛅️ Partly Cloudy, 65°F"
    private static let weatherRainy       = "🌧 Light Rain, 55°F"
    private static let weatherSnow        = "❄️ Light Snow, 28°F"
    private static let weatherFog         = "🌫 Foggy, 60°F"
    private static let weatherMostlySunny = "🌤 Mostly Sunny, 68°F"

    private static func entryPlan() -> [Blueprint] {
        // 30 entries spread over 30 days. Days 5, 12, 19, 26 deliberately skipped
        // so the streak insight has variety.
        let dayOffsets: [Int] = [
            0, 1, 2, 3, 4,  6, 7, 8, 9, 10, 11,
            13, 14, 15, 16, 17, 18,
            20, 21, 22, 23, 24, 25,
            27, 28, 29, 30, 31, 32, 33
        ]

        let blueprints: [Blueprint] = [
            // 0 — today
            Blueprint(
                daysAgo: dayOffsets[0], hour: 21, minute: 30,
                title: "A quiet evening",
                content: "Closed the laptop early tonight. **Made tea**, sat with the cat, read a chapter of the new novel without checking my phone.\n\nThe small ritual matters more than I thought it would. I notice I sleep better when the last hour is mine.",
                mood: .good, template: .freeWrite,
                weather: weatherPartlyCloud, location: sf,
                tags: ["evening", "mindfulness", "reflection"],
                insights: [
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive")),
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "evening, ritual, sleep"))
                ],
                writingDuration: 220, sentiment: 0.55
            ),
            // 1 — yesterday
            Blueprint(
                daysAgo: dayOffsets[1], hour: 7, minute: 15,
                title: "Morning Pages",
                content: "Wake up. Brain already running.\n\nThree things I want to do today: finish the design review, call mom, run for 20 minutes. That's it. Anything else is bonus.\n\nIt feels good to put it on paper instead of carrying it in my head.",
                mood: .good, template: .morningPages,
                weather: weatherSunny, location: sf,
                tags: ["morning", "goals", "reflection"],
                insights: [InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "morning, design review, run"))],
                writingDuration: 180, sentiment: 0.45
            ),
            // 2 — bookmarked, gratitude
            Blueprint(
                daysAgo: dayOffsets[2], hour: 22, minute: 0,
                title: "Three good things",
                content: "**Three good things from today:**\n\n1. The barista at the corner café knew my order without asking.\n2. A long walk through Golden Gate Park with no destination.\n3. A friend texted just to say hi — no agenda, no ask.\n\nI noticed I held my breath less today. Gratitude works on me even when I don't believe in it.",
                mood: .great, template: .gratitude,
                weather: weatherMostlySunny, location: sf,
                tags: ["gratitude", "evening", "mindfulness"],
                insights: [
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive")),
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "gratitude, friendship, walk"))
                ],
                writingDuration: 320, sentiment: 0.78
            ),
            // 3
            Blueprint(
                daysAgo: dayOffsets[3], hour: 18, minute: 45,
                title: "Run on the bridge",
                content: "Long run today — 40 minutes along the Embarcadero. The fog was rolling in just as I crossed the halfway point. **Lungs burned, then opened.**\n\nWhy do I always feel like a different person after exercise? It's not just chemistry. There's something honest about the body when it's tired.",
                mood: .great, template: .freeWrite,
                weather: weatherFog, location: sf,
                tags: ["exercise", "evening", "reflection"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.health"))],
                writingDuration: 240, sentiment: 0.62
            ),
            // 4 — pinned, weekly review
            Blueprint(
                daysAgo: dayOffsets[4], hour: 20, minute: 0,
                title: "Week in review",
                content: "**What went well**\n- Shipped the dashboard refactor without any regressions reported.\n- Read 80 pages this week — most since January.\n- Cooked at home five nights out of seven.\n\n**What didn't**\n- Skipped the gym Wednesday. Felt it Thursday and Friday.\n- Got pulled into a 90-minute Slack thread that should have been a 5-minute decision.\n\n**Next week**\n- Block Wednesday morning for the gym, no exceptions.\n- Reply to the design review feedback by Tuesday.\n- One creative session — back to the watercolor sketches.",
                mood: .good, template: .weeklyReview,
                weather: weatherPartlyCloud, location: sf,
                tags: ["reflection", "goals", "evening"],
                insights: [
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "review, gym, design")),
                    InsightSpec(type: .pattern, content: String(localized: "ai.theme.work"))
                ],
                writingDuration: 540, sentiment: 0.42
            ),
            // 5
            Blueprint(
                daysAgo: dayOffsets[5], hour: 12, minute: 30,
                title: "Lunch break thoughts",
                content: "Walked over to Mission for tacos. Took 25 minutes to actually leave my desk — Slack kept finding new ways to keep me sitting.\n\n**Lesson:** when I tell myself \"just one more thing,\" the answer is to stand up.",
                mood: .neutral, template: .freeWrite,
                weather: weatherSunny, location: sf,
                tags: ["work", "reflection"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.work"))],
                writingDuration: 90, sentiment: 0.05
            ),
            // 6
            Blueprint(
                daysAgo: dayOffsets[6], hour: 7, minute: 30,
                title: "Quiet morning",
                content: "Woke up before the alarm. Coffee, the long way — grinder, pour-over, no laptop in sight for the first 20 minutes.\n\nI keep thinking the productive thing is to start the day with email. The truth is the **opposite** is what makes the rest of the day work.",
                mood: .good, template: .morningPages,
                weather: weatherMostlySunny, location: sf,
                tags: ["morning", "mindfulness", "reflection"],
                insights: [InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive"))],
                writingDuration: 160, sentiment: 0.50
            ),
            // 7 — CBT three column, frustration
            Blueprint(
                daysAgo: dayOffsets[7], hour: 19, minute: 10,
                title: "After the meeting",
                content: "**Situation:** Project review meeting where the lead pushed back hard on my proposal in front of the team.\n\n**Automatic thought:** \"He thinks I'm not technical enough. Everyone in the room agrees with him. I should have stayed quiet.\"\n\n**Rational response:** He pushed back on the *proposal*, not on me. He's pushed back equally hard on three other people in the same role. Two of his points were actually fair, and the team chimed in to refine the idea, not bury it. The fact that I cared enough to bring a proposal is the opposite of \"not technical enough.\"\n\nFelt smaller after the meeting. Bigger after writing this.",
                mood: .bad, template: .cbtThreeColumn,
                weather: weatherRainy, location: sf,
                tags: ["work", "reflection"],
                insights: [
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.negative")),
                    InsightSpec(type: .pattern, content: String(localized: "ai.cbt.mindReading.1"))
                ],
                writingDuration: 480, sentiment: -0.45
            ),
            // 8
            Blueprint(
                daysAgo: dayOffsets[8], hour: 21, minute: 15,
                title: "Dinner with mom",
                content: "Dinner at her place. She made the eggplant thing she used to make on Sundays. Nothing big happened — and that was the **whole point**.\n\nI have to remember that the people who knew you when you were small are the only ones who remember the actual version of you.",
                mood: .great, template: .freeWrite,
                weather: weatherPartlyCloud, location: sf,
                tags: ["family", "gratitude", "evening"],
                insights: [
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "family, dinner, mom")),
                    InsightSpec(type: .pattern, content: String(localized: "ai.theme.relationships"))
                ],
                writingDuration: 250, sentiment: 0.68
            ),
            // 9 — Tokyo travel
            Blueprint(
                daysAgo: dayOffsets[9], hour: 23, minute: 0,
                title: "First night in Tokyo",
                content: "Got in this morning. Slept four hours on the plane and felt the city in my bones the moment the train hit Shinjuku.\n\nWalked from the hotel to a tiny ramen place I had bookmarked, tucked into a counter seat next to two salarymen who were also alone. Nobody spoke. The bowl was perfect.\n\n**Notes:** the silence here is different. It's not absence — it's a positive thing. People give each other room.",
                mood: .great, template: .freeWrite,
                weather: weatherPartlyCloud, location: tyo,
                tags: ["travel", "evening", "reflection"],
                insights: [
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "travel, Tokyo, ramen")),
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive"))
                ],
                writingDuration: 360, sentiment: 0.72
            ),
            // 10 — Tokyo
            Blueprint(
                daysAgo: dayOffsets[10], hour: 19, minute: 30,
                title: "Tsukiji and the long walk back",
                content: "Up at 5 for the outer market. Tamagoyaki on a stick, tea so strong it tasted like the inside of a teapot.\n\nWalked back through Ginza, then a long detour through a residential side street. A grandmother was watering plants on the sidewalk and bowed slightly as I passed. **Everywhere I look, attention. Nothing I look at is invisible.**",
                mood: .great, template: .freeWrite,
                weather: weatherSunny, location: tyo,
                tags: ["travel", "morning", "mindfulness"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.creativity"))],
                writingDuration: 290, sentiment: 0.75
            ),
            // 11 — bookmarked, NYC business
            Blueprint(
                daysAgo: dayOffsets[11], hour: 8, minute: 0,
                title: "Red-eye to JFK",
                content: "Six hours of broken sleep and a coffee that tastes like it was brewed two presidencies ago. Keynote rehearsal at 10. I'll be fine — I always am.\n\n**Fear:** that I'll forget the third slide.\n**Reality:** I have not, in 14 years, forgotten a slide.",
                mood: .neutral, template: .morningPages,
                weather: weatherPartlyCloud, location: nyc,
                tags: ["travel", "work", "morning"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.cbt.catastrophizing.1"))],
                writingDuration: 150, sentiment: 0.10
            ),
            // 12 — NYC
            Blueprint(
                daysAgo: dayOffsets[12], hour: 22, minute: 30,
                title: "Talk landed",
                content: "The talk landed. The questions were better than the talk.\n\nA student in the front row asked something I didn't have a clean answer for, and I said \"I don't know — what do *you* think?\" and the room actually leaned forward. **Note to self:** stop performing certainty. People trust me more when I don't.",
                mood: .great, template: .dailyReview,
                weather: weatherMostlySunny, location: nyc,
                tags: ["work", "reflection", "evening"],
                insights: [
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive")),
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "talk, students, certainty"))
                ],
                writingDuration: 380, sentiment: 0.81
            ),
            // 13
            Blueprint(
                daysAgo: dayOffsets[13], hour: 14, minute: 0,
                title: "Bryant Park",
                content: "Ate lunch under the trees in Bryant Park. A jazz trio was playing on the lawn. Nobody had headphones in. **Strange and excellent.**",
                mood: .good, template: .freeWrite,
                weather: weatherSunny, location: nyc,
                tags: ["travel", "mindfulness"],
                insights: [InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "park, music, lunch"))],
                writingDuration: 110, sentiment: 0.50
            ),
            // 14 — bad, sleep
            Blueprint(
                daysAgo: dayOffsets[14], hour: 23, minute: 45,
                title: "Insomnia again",
                content: "Up at 3, then 4, then gave up at 4:30 and watched the ceiling. The hotel pillows are wrong, the sirens come in waves, and my brain started a presentation it has no business writing.\n\n**Tomorrow:** stop the slide deck before 9pm. Walk to the river. Skip the second coffee.",
                mood: .bad, template: .freeWrite,
                weather: weatherRainy, location: nyc,
                tags: ["sleep", "evening", "work"],
                insights: [
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.negative")),
                    InsightSpec(type: .pattern, content: String(localized: "ai.theme.health"))
                ],
                writingDuration: 200, sentiment: -0.40
            ),
            // 15 — Seattle
            Blueprint(
                daysAgo: dayOffsets[15], hour: 11, minute: 0,
                title: "Pike Place",
                content: "Layover in Seattle. Wandered to Pike Place because I was told to. The salmon throwing was exactly as advertised and **somehow not less charming for it**. Ate a piroshki standing up. Watched two guys argue passionately about espresso ratios.\n\nReminded me to talk about things I love with the same intensity. Even the small ones.",
                mood: .good, template: .freeWrite,
                weather: weatherFog, location: sea,
                tags: ["travel", "creative", "morning"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.creativity"))],
                writingDuration: 230, sentiment: 0.55
            ),
            // 16
            Blueprint(
                daysAgo: dayOffsets[16], hour: 7, minute: 0,
                title: "Snow morning",
                content: "First real snow of the year overnight. The street is silent in that specific way only snow makes a street silent. Cat is in the window watching like she's never seen anything stranger.\n\n**Plan today:** nothing. The world has paused; so will I.",
                mood: .great, template: .morningPages,
                weather: weatherSnow, location: sea,
                tags: ["morning", "mindfulness", "reflection"],
                insights: [InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive"))],
                writingDuration: 175, sentiment: 0.66
            ),
            // 17 — Lisbon, creative
            Blueprint(
                daysAgo: dayOffsets[17], hour: 18, minute: 30,
                title: "Sketching at Miradouro",
                content: "Climbed the steps to Graça with the watercolor kit. Two hours filling a single page. Got the light wrong — but the light here is wrong in a way I want to keep getting wrong.\n\n**Truth:** I've made one painting a week for six months and I still don't think I'm a painter. Maybe that's the point. The verb matters more than the noun.",
                mood: .great, template: .freeWrite,
                weather: weatherSunny, location: lis,
                tags: ["creative", "travel", "reflection"],
                insights: [
                    InsightSpec(type: .pattern, content: String(localized: "ai.theme.creativity")),
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "sketching, watercolor, Lisbon"))
                ],
                writingDuration: 410, sentiment: 0.72
            ),
            // 18 — Lisbon
            Blueprint(
                daysAgo: dayOffsets[18], hour: 22, minute: 0,
                title: "Fado bar",
                content: "Tiny room. Twelve tables. The singer closed her eyes and the whole bar held its breath at the same time.\n\nI don't speak Portuguese. Didn't need to.",
                mood: .great, template: .freeWrite,
                weather: weatherPartlyCloud, location: lis,
                tags: ["travel", "evening", "creative"],
                insights: [InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "fado, music, evening"))],
                writingDuration: 160, sentiment: 0.85
            ),
            // 19 — back home, neutral
            Blueprint(
                daysAgo: dayOffsets[19], hour: 14, minute: 0,
                title: "Reentry",
                content: "Back home. Suitcase still in the hallway. Two weeks of email looks worse than it is — the **important** thread count is always smaller than the unread count.\n\nGoing to triage one hour today and one hour tomorrow. That's it.",
                mood: .neutral, template: .dailyReview,
                weather: weatherPartlyCloud, location: sf,
                tags: ["work", "reflection"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.work"))],
                writingDuration: 130, sentiment: 0.10
            ),
            // 20 — terrible, conflict
            Blueprint(
                daysAgo: dayOffsets[20], hour: 22, minute: 30,
                title: "Hard call",
                content: "Hard conversation with a friend tonight. Long-running thing finally got named.\n\nI cried. I haven't cried in a year and a half. Some part of me has been waiting for permission.\n\n**No conclusions tonight.** Just want to write the date down so I know the day this happened.",
                mood: .terrible, template: .freeWrite,
                weather: weatherRainy, location: sf,
                tags: ["family", "reflection", "evening"],
                insights: [
                    InsightSpec(type: .sentiment, content: String(localized: "ai.insight.negative")),
                    InsightSpec(type: .pattern, content: String(localized: "ai.theme.relationships"))
                ],
                writingDuration: 220, sentiment: -0.78
            ),
            // 21 — recovery
            Blueprint(
                daysAgo: dayOffsets[21], hour: 9, minute: 0,
                title: "Walk before work",
                content: "Couldn't sleep past six. Walked two miles before work. The city was just waking up — fog burning off the bridge, a few runners, the bakery on 18th already pulling sourdough.\n\nI feel like I aged a year overnight. **In a good way.** The thing that needed to be said got said.",
                mood: .good, template: .morningPages,
                weather: weatherFog, location: sf,
                tags: ["morning", "exercise", "reflection"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.health"))],
                writingDuration: 195, sentiment: 0.40
            ),
            // 22 — bookmarked, daily review
            Blueprint(
                daysAgo: dayOffsets[22], hour: 21, minute: 0,
                title: "Best & worst",
                content: "**Best:** finally read the chapter on Stoic practice without rolling my eyes once. Marked four lines.\n\n**Worst:** ate lunch at my desk again. I keep telling myself I'll stop and then I look up and it's 4pm.\n\n**Tomorrow:** lunch outside, no screens, no exceptions.",
                mood: .good, template: .dailyReview,
                weather: weatherMostlySunny, location: sf,
                tags: ["evening", "reflection", "goals"],
                insights: [InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "lunch, reading, stoic"))],
                writingDuration: 240, sentiment: 0.30
            ),
            // 23
            Blueprint(
                daysAgo: dayOffsets[23], hour: 6, minute: 30,
                title: "Long run",
                content: "10 miles along Ocean Beach. **Cold air, empty trail, mind blank by mile 4.** This is the only kind of meditation that has ever worked on me.",
                mood: .great, template: .freeWrite,
                weather: weatherFog, location: sf,
                tags: ["exercise", "morning", "mindfulness"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.health"))],
                writingDuration: 95, sentiment: 0.62
            ),
            // 24
            Blueprint(
                daysAgo: dayOffsets[24], hour: 19, minute: 45,
                title: "Cooking again",
                content: "Made the soup my grandmother used to make. Got the broth almost right. The dumplings need more salt.\n\nI keep trying because I want my future kids to taste the same soup, and that means I have to know how to make it without the recipe in front of me.",
                mood: .good, template: .freeWrite,
                weather: weatherPartlyCloud, location: sf,
                tags: ["family", "creative", "evening"],
                insights: [
                    InsightSpec(type: .pattern, content: String(localized: "ai.theme.relationships")),
                    InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "soup, grandmother, cooking"))
                ],
                writingDuration: 290, sentiment: 0.55
            ),
            // 25 — neutral
            Blueprint(
                daysAgo: dayOffsets[25], hour: 13, minute: 0,
                title: "Blank afternoon",
                content: "Productive in a tiny way. Cleared a backlog of tabs, paid two bills, replied to three texts I'd been sitting on. **Not exciting. Counts anyway.**",
                mood: .neutral, template: .dailyReview,
                weather: weatherSunny, location: sf,
                tags: ["work", "reflection"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.work"))],
                writingDuration: 120, sentiment: 0.05
            ),
            // 26 — gratitude
            Blueprint(
                daysAgo: dayOffsets[26], hour: 22, minute: 15,
                title: "Three small things",
                content: "1. The neighbor's dog stopped at my door for a hello.\n2. A song I forgot I loved came on while I was cooking.\n3. The library hold for the book I've been waiting on came in.\n\nGood day for a Tuesday.",
                mood: .good, template: .gratitude,
                weather: weatherMostlySunny, location: sf,
                tags: ["gratitude", "evening", "mindfulness"],
                insights: [InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive"))],
                writingDuration: 135, sentiment: 0.60
            ),
            // 27
            Blueprint(
                daysAgo: dayOffsets[27], hour: 7, minute: 45,
                title: "First snow at home",
                content: "Snow on the hills outside the window. The first I can remember in this city. Pulled the curtain back like a kid.\n\n**Reminder:** the world is allowed to surprise you.",
                mood: .great, template: .morningPages,
                weather: weatherSnow, location: sf,
                tags: ["morning", "mindfulness"],
                insights: [InsightSpec(type: .sentiment, content: String(localized: "ai.insight.positive"))],
                writingDuration: 95, sentiment: 0.70
            ),
            // 28 — work, neutral
            Blueprint(
                daysAgo: dayOffsets[28], hour: 16, minute: 30,
                title: "Stuck on the spec",
                content: "Stuck on the auth spec for two hours. Couldn't decide between two designs that are both fine. **The decision matters less than making one.**\n\nGoing to walk for 15 minutes and pick the one I think of first when I sit back down.",
                mood: .neutral, template: .freeWrite,
                weather: weatherPartlyCloud, location: sf,
                tags: ["work", "reflection"],
                insights: [InsightSpec(type: .pattern, content: String(localized: "ai.theme.work"))],
                writingDuration: 110, sentiment: 0.05
            ),
            // 29 — 33 days ago
            Blueprint(
                daysAgo: dayOffsets[29], hour: 21, minute: 30,
                title: "Started the journal",
                content: "Today I'm starting this. **One short entry a day.**\n\nNot for anyone. Not for the future. Just to see what happens when I tell myself the truth in writing for a month.",
                mood: .good, template: .freeWrite,
                weather: weatherSunny, location: sf,
                tags: ["reflection", "goals"],
                insights: [InsightSpec(type: .topicExtraction, content: String(format: String(localized: "ai.insight.topics"), "journal, start, intention"))],
                writingDuration: 75, sentiment: 0.45
            )
        ]
        return blueprints
    }
}
